### ISSUE TITLE
در مارشمالو/ لالی‌پاپ نمیشود ویجت لاک‌اسکرین گذاشت

### ISSUE THREAD

**Issue by Arya766** [ebraminio/DroidPersianCalendar#106]

**Comment by ebraminio** [comment]
متأسفانه این قابلیت از اندروید ۵ حذف شده است
"The widgetCategory attribute declares whether your App Widget can be displayed on the home screen (home_screen), the lock screen (keyguard), or both. Only Android versions lower than 5.0 support lock-screen widgets. For Android 5.0 and higher, only home_screen is valid."
http://developer.android.com/guide/topics/appwidgets/index.html
