### ISSUE TITLE
 عدم نمایش رویداد های حساب های دیگر

### ISSUE THREAD

**Issue by ghost** [ebraminio/DroidPersianCalendar#116]
برای مثال کارهای روزانه در حساب گوگل و تولد افراد در حساب فیسبوک نمایش داده نمی‌شود.

**Comment by aliyargholi** [comment]
رویدادهای اضافه شده از داخل تقویم به گوگل کلندر ملحق میشود و اثری از آن در خود تقویم موجود نیست.

**Comment by ebraminio** [comment]
در نسخهٔ بعد کمی بهتر می‌شود :)
