### ISSUE TITLE
ارسال آیکون‌های نوتیفیکیشن‌بار جدید در ایمیل شما

### ISSUE THREAD

**Issue by mhamm1024** [ebraminio/DroidPersianCalendar#117]
آیکون شماره روز در نوتیفیکیشن‌بار در دایره سفید قرار می‌گیرد.

**Comment by ebraminio** [comment]
ممنون دوست گرامی، هرچند ایمیلی دریافت نشد، با وجود اینکه به نظر من هم نبود آیکون هم جالب نیست ولی الآن با نسخهٔ جدیدی که تا چند ساعت دیگر منتشر می‌شود با اطلاق رنگی تقریباً متداول برای دایره حداقل قابل تحمل‌تر شده و با توجه به اینکه مشابه ظاهر اندروید نیز شده قابل عادت کردن هم می‌شود. امیدوارم نسخهٔ جدید از نظر شما نیز بهتر شده باشد  به همین دلیل این ایشو را برای الآن می‌بندم

**Comment by mhamm1024** [comment]
https://drive.google.com/file/d/0BzFXQYmOzElwVTRVSjVLcnkzVlFfb0ZBMVVDajA5eUpLZGdZ/view?usp=docslist_api

**Comment by behdad222** [comment]
@ebraminio برای من فرستاده بودند :)

**Comment by mhamm1024** [comment]
این فایل رو دانلود کنید و تغییرات رو اعمال کنید.
