### ISSUE TITLE
ناهماهنگی زبانی در ویجت جدید

### ISSUE THREAD

**Issue by mahdavi75** [ebraminio/DroidPersianCalendar#119]
با اینکه زبان اپلیکیشن روی فارسی تنظیم شده اما گاهی اوقات بطور اتوماتیک و ناخواسته، زبان ویجت جدید به انگلیسی تغییر می‌کند

مثلا:
بجای نیمه‌شب شرعی، Midnight

این اتفاق بیشتر (و نه همیشه) زمانی رخ‌می‌دهد که اسکرین را آنلاک می‌کنم. البته در موارد دیگر به‌غیر از آنلاک اسکرین هم مشاهده شد. هنوز نتوانسته‌ام الگوی منظمی پیدا کنم که دقیقا چه زمانی این گونه می‌شود
تصور می‌کنم که اپلیکیشن بطور موقت زبان پیش‌فرض دستگاه (که برای من انگلیسی است) را به عنوان زبان مورد استفاده خود برمی‌گزیند
که البته با یکبار کلیک بر روی ویجت و وارد شدن به اپلیکیشن، سپس خارج شدن از آن، شرایط به حالت عادی باز می‌گردد
v5.0.2
Android v6.0.1
Nexus 5

**Comment by ebraminio** [comment]
سلام دوست عزیز، این مشکل در حال حاضر برطرف شده و به خاطر یادآوریتون سعی می‌کنیم هر چی زودتر نسخهٔ جدید که شامل اصلاح این مشکل هست رو منتشر کنیم
