### ISSUE TITLE
وسط‌ چین و بزرگ کردن سایز فونت ویجت

### ISSUE THREAD

**Issue by ghost** [ebraminio/DroidPersianCalendar#121]
لطفا این تغیرات را اعمال کنید:
- سایر ویجت از تنظیمات برنامه قابل تغییر باشد.
- ویجت وسط چین شود.
- فونت ویجت B Yekan شود.

**Comment by carp3** [comment]
امکان تغییر قلم با توجه به مجوز نشر فونت های شرکت برنا رایانه امکان پذیر نیست.

**Comment by ebraminio** [comment]
وسط‌چین کردن اضافه شد، مانده تغییر اندازه که در #351 اینجا پیگیری خواهیم کرد :)
