### ISSUE TITLE
عدم تغییر نام روز در نوتیفیکیشن

### ISSUE THREAD

**Issue by Arya766** [ebraminio/DroidPersianCalendar#124]
با سلام، در نسخه ۵.۰.۵ پس از تغییر روز (مثلا از سه‌شنبه به چهارشنبه) نام روز (سه‌شنبه) در نوتیفیکیشن بار تغییر نمی‌کند، و کمکان همام (سه‌شنبه) را نمایش می‌دهد.
متشکرم

**Comment by ebraminio** [comment]
مشکل روز هفتهٔ اشتباه در ۵.۰.۶ برطرف شد، ممنون
