### ISSUE TITLE
پرش به یک تاریخ خاص

### ISSUE THREAD

**Issue by carp3** [ebraminio/DroidPersianCalendar#125]
با سلام.  
اگر امکان پریدن به یک سال خاص یا یک تاریخ خاص در تقویم وجود داشته باشه خیلی عالیه.  مثلا برای دیدن تعطیلات عید سال آینده باید 12 صفحه بریم جلو.  برای سالهای قبل یا بعد نیازه ده ها صفحه عوض بشه که کمی خسته کننده. 
با تشکر.

**Comment by ebraminio** [comment]
با تشکر نسخهٔ بعد مجهز به این ویژگی خواهد بود
