### ISSUE TITLE
نمایش نامناسب رویداد های طولانی

### ISSUE THREAD

**Issue by carp3** [ebraminio/DroidPersianCalendar#126]
همانطور که در تصویر زیر میبینید،  رویداد های طولانی درست ورپ نمیشند و قسمتی از متن از بین میره 
![quickmemo _2016-03-13-20-17-04](https://cloud.githubusercontent.com/assets/1427433/13730031/de3aae5a-e958-11e5-8984-eaa1d78361a6.png)

**Comment by ebraminio** [comment]
ادغام در https://github.com/ebraminio/DroidPersianCalendar/issues/77
