### ISSUE TITLE
Localize

### ISSUE THREAD

**Issue by lovebdsobuj** [ebraminio/DroidPersianCalendar#130]
Asslamu Alaikum,

**DroidPersianCalendar** Very eye-catching design+development!

Sir,
I want to localize this application for our country, can you help me to do that? I'm form Bangladesh.

**Comment by ebraminio** [comment]
It would be appreciated of course but do you happen to use [Solar Hijri Calendar](https://en.wikipedia.org/wiki/Solar_Hijri_calendar) on Bangladesh? If not, there would be not much point on localizing the app I'm afraid :(

**Comment by lovebdsobuj** [comment]
How Can I display English calendar?

**Comment by lovebdsobuj** [comment]
Means, If

**Comment by lovebdsobuj** [comment]
Mistakenly, I closed this thread.  
---
and I'm really sorry, becuase I can't clear my point.

When user change app Language via Settings to English, Calendar will be display as English (georgian).
![screenshot_00132_08h39m23s](https://cloud.githubusercontent.com/assets/10352682/14057610/462185cc-f32f-11e5-8c4b-ab0852d1a249.png)

**Comment by ebraminio** [comment]
Hmm, honestly I didn't imagined about non-Persian calendar use from the app from the beginning but you are right, definitely something worth to do at some point.

**Comment by lovebdsobuj** [comment]
So, we can wait for this updates... :star: :star: :star: :star: :star:

**Comment by Lokesh-Krishna** [comment]
I'm sorry about bumping the issue but is this still under consideration?
The app is simply gorgeous and offering support for the Gregorian calendar(the most widely used calendar on the planet) would open it up to a vastly larger audience.
If not as an option in this app, maybe as a separate app?

**Comment by ebraminio** [comment]
Thanks for your interest guys. Honestly, we made lots of calendar specific decisions on the designing, e.g. using RTL layout by default and capabilities very specific to Iranians (holidays and such) so this is a bit hard to do and I am a student right now and can afford just a limited time for the app :(

**Comment by ebraminio** [comment]
The next version will be much better on this area and supports Gregorian calendar as a default calendar (but should be enabled from setting). We will try to make that even better but closing this for now :)

**Comment by lokesh-krishna** [comment]
Just curious but are you also planning on changing the name to reflect this change? The present name doesn't help much with discovery.

**Comment by ebraminio** [comment]
Yes, no idea there yet :/ We need also some first time user wizard for choosing preferences, that is also hard :/

**Comment by ebraminio** [comment]
@lovebdsobuj @lokesh-krishna Hey there, have you looked into the new versions? There is an option will be shown on the new installation when clicked the app automatically switch to English and Gregorian calendar. I guess that will be helpful, can you check that? Thanks!

**Comment by ebraminio** [comment]
@lovebdsobuj Hi, is there any interest on translating this to Bengali? The next version can have the app in Bengali by default for new users if the translation happens :) It can have Gregorian as the default calendar on the language also but including Hijra calendar also.
