### ISSUE TITLE
دریافت مختصات از جی‌پی‌اس

### ISSUE THREAD

**Issue by mhamm1024** [ebraminio/DroidPersianCalendar#131]
در برنامه، توانایی دریافت مختصات از جی‌پی‌اس وجود ندارد، این ویژگی سبب می‌شود که اوقات شرعی برای کل نقاط مختلف دنیا در دسترس باشد.

**Comment by ebraminio** [comment]
انجامش سخت نیست منتهی هدف اولیهٔ ایجاد این برنامه نگرفتن دسترسی بود به همین با وجود اینکه کد آن را نوشته بودم آن را حذف کردم ولی به قول یکی از دوستان از آنجایی که برنامه متن‌باز است کاربر نگرانی دادن دسترسی نخواهد داشت و به همین شاید این کار را بالاخره انجام دادم.

**Comment by ebraminio** [comment]
الآن قابلیتش پیاده‌سازی شده و احتمالاً در نسخهٔ بعد خواهد آمد. ممنون
