### ISSUE TITLE
اولویت در نمایش اوقات شرعی بعدی

### ISSUE THREAD

**Issue by tabarak105** [ebraminio/DroidPersianCalendar#138]
سلام
لطفا قابلیتی اضافه کنید که اولین اوقات شرعی که نمایش داده میشه 
اولین اوقات شرعی بعدی باشد
مثلا از اذان ظهر که گذشت
بالاتری اوقاتی که نمایش داده میشه اذان عصر یا اذان مغرب باشد
تشکر از بهترین برنامه اندروید

**Comment by behdad222** [comment]
در این ایشو پیگیری میشه
https://github.com/ebraminio/DroidPersianCalendar/issues/133
