### ISSUE TITLE
اضافه کردن شهری های زیارتی مهم مثل نجف و کربلا 

### ISSUE THREAD

**Issue by tabarak105** [ebraminio/DroidPersianCalendar#139]

**Comment by ebraminio** [comment]
سلام گرامی، چون افزودن شهرها انتهای نخواهد داشت از چند نسخهٔ پیش افزودن از جی‌پی‌اس به برنامه اضافه شده است، پیشنهاد می‌کنم از آن استفاده کنید و اگر مشکلی داشت مطلع کنید،‌ با تشکر :)
