### ISSUE TITLE
 امکان تاریخ تولد

### ISSUE THREAD

**Issue by ebraminio** [ebraminio/DroidPersianCalendar#146]
از ایمیل‌های رسیده

**Comment by ebraminio** [comment]
انجام شد، در نسخه بعد :)

**Comment by peyman974** [comment]
قبل از اینکه این پیشنهاد را ارسال کنم اینجا را دیدم ولی مثل اینکه این مورد تولد هنوز اضافه نشده اگر بتوانید تاریخ تولد را به یادآوری اضافه کنید که مثلا زودتر با تنظیم تعداد روز مورد نظر مانده به یادآوری اعلام کند و هر سال نیازی به وارد کردن مجدد یادآوری نباشد این مورد می تواند برای یادآوری های تکراری یکی از قابلیتهای مفید باشد که برنامه شمارا کاملتر کند با سپاس
