### ISSUE TITLE
اغلب زمانهای اذان مشهد صحیح نیست

### ISSUE THREAD

**Issue by ehsanzrb** [ebraminio/DroidPersianCalendar#148]

**Comment by ebraminio** [comment]
امکان دارد در اینجا http://praytimes.org/code/v2/js/examples/monthly.htm
با
Latitude: 34.3 Longitude: 59.57 (مختصات استفاده شده برای مشهد در برنامه)
Time Zone: 3.5
Method: آخرین گزینه (Tehran)

آزمایش کنید و ببینید نتیجه با آنچه مد نظرتان است مطابقت دارد؟
