### ISSUE TITLE
عدم نمایش صحیح تاریخ در lock screen

### ISSUE THREAD

**Issue by masoudm67** [ebraminio/DroidPersianCalendar#149]
سلام
ممنون بابت برنامه بسیار خوبتون

تاریخ در lock screen تغیری نمیکند و تاریخ روشن شدن گوشی 
را نشان میدهد
لطفا برای حل این مشکل راهنمایی بفرمایید
گوشی LG K10
ممنونم

**Comment by behdad222** [comment]
@masoudm67 دلیل اصلی این موضوع کم بودن رم دستگاه  و بسته شدن سرویس تقویم هست
با باز کردن دوباره برنامه دیتا آپدیت می‌شود
سعی میکنیم در نسخه‌های بعد این مشکل برطرف کنیم

**Comment by Baft** [comment]
note5 - android 6 &7
مشکل رم وکندی وجود ندارد
تاریخ در لاک اسکرین ثابت میماند

**Comment by ebraminio** [comment]
با استفاده از ورکر احتمالاً وضع کمی بهتر شده باشد، در غیر اینصورت واقعاً دیگر ایده‌ای برای حل آن نداریم :/ با تشکر

**Comment by ebraminio** [comment]
که در نسخهٔ جدید قابل مشاهده است
