### ISSUE TITLE
MavenCentral dependency

### ISSUE THREAD

**Issue by developerandios** [ebraminio/DroidPersianCalendar#150]
سلام خدا قوت
mishe az maven central be onvane dependency tu gradle gharar dad? ag in emkan faraham beshe kheili estefade kardan rahat mishe.
mamnun

**Comment by mas68** [comment]
آره استفاده بعنوان کتابخانه

**Comment by ebraminio** [comment]
به نظر به اندازهٔ مخزن فعلی به روز نیستند و برنامه‌ای برای آن وجود ندارد

همچنین به دلیل استفاده کتابخانه‌های جی‌پی‌ال در این برنامه: https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)
