### ISSUE TITLE
Notification Priority

### ISSUE THREAD

**Issue by Azadfar2009** [ebraminio/DroidPersianCalendar#151]
سلام خدمت شما مهندس عزیز
ممنون بابت برنامه خوبتون
می خواستم یک باگ معرفی کنم : 
در اندروید 6 (گوشی سونیD6503) وقتی روی یک روز مشخص نگه میداریم، 
برنامه Calendar با مشکل فورس کلوز مواجه میشه !

![photo_2016-09-11_13-26-29](https://cloud.githubusercontent.com/assets/22128625/18416244/a3fb8a5c-7823-11e6-8ffa-1a9d85cb904a.jpg)

و یک پیشنهاد برای قسمت ناتیفیکش بار دارم
اگر امکانش هست قابلیت Notification Priority (اولویت اعلان ها) رو به برنامه ی خیلی خوبتون اضافه کنید
چون تو همه حالت ها اولیت اول رو داره و شما هربار ناکیفیکش پنل رو باز میکنید اولین برنامه است و خوب گاهی آزاردهنده میباشد !
اگه بشه حالت Minimum رو اضافه کنید عالی میشه
یعنی تو حالت عادی نمایش داده نمیشه و وقتی پنل رو باز میکنید جدا از دیگر برنامه ها در آخر لیست ناتیفیکش ها قرار میگیره !

![photo_2016-09-11_13-26-21](https://cloud.githubusercontent.com/assets/22128625/18416251/2480c494-7824-11e6-9e2e-b9b162681571.jpg)

پیشاپیش ممنون از توجهتون و برنامه ی بسیار خوب و کاربردیتون ^_^ 👍

**Comment by ebraminio** [comment]
مشکل اول ظاهرا از سامسونگ بوده و برطرف شده، مشکل دوم هم احتمالا چنین حالتی دارد چون در اصل برنامه اولویت پایینی می‌گیرد که در اندرویدهای آزملیش شده و نزدیک به استاندارد بدون مشکلی کار می‌کند
