### ISSUE TITLE
نمایش عددی تاریخ در ویجت مثل 1395/8/7

### ISSUE THREAD

**Issue by mansourmasoumi** [ebraminio/DroidPersianCalendar#154]
سلام خیلی ممنون بابت تلاشتون
1-اگه به جای 1395/آبان/7 بشه نوشت 7/8/1395 فکر کنم زیباتر باشه
2-یه ویجت بدون روز هفته داشته باشه یعنی فقط تاریخ کاملا عددی

**Comment by mansourmasoumi** [comment]
سلام دوباره 
نمایش مناسبت ها در ویجت هم بهتره اختیاری باشه

**Comment by ebraminio** [comment]
انجام شد :)
