### ISSUE TITLE
نحوه افزودن به یک پروژه در اندروید استودیو

### ISSUE THREAD

**Issue by sourena21** [ebraminio/DroidPersianCalendar#155]
سلام
من نمی تونم این پروژه رو به پروژه خودم تو اندروید استودیو اضافه کنم
میشه راهنمایی کنید چه جوری باید این کارو کنم؟
ممنونم

**Comment by armoun** [comment]
@sourena21 
سلام از این آموزش استفاده کن
باید اون یکی رو به صورت ماژول به برنامه اصلیت اضافه کنی
اینجا توضیح داده
`http://www.philosophicalhacker.com/2014/10/03/an-alternative-multiproject-setup-for-android-studio/`

**Comment by sourena21** [comment]
چرا کپی نمیشه لینکش :))

**Comment by sourena21** [comment]
خیلی پیچیده و سخته
کمی توضیح میدی راجع بهش؟

**Comment by armoun** [comment]
@sourena21
File -> Import Project ...

1- یه پوشه به اسم کتابخونه تو پروژه اصلی
2- ریختن پروژه دوم تو پوشه کتابخونه
3-حذف بخش هایی از فایل منیفست پروژه دوم
4-کامپایل کردن پروژه دوم تو دیپندنسی و ستینگ گریدل

اینم یه نمونه از همین دسته پروژه ها
https://github.com/emilsjolander/StickyListHeaders
