### ISSUE TITLE
اشکال در پخش اذان صبح

### ISSUE THREAD

**Issue by smtaheri** [ebraminio/DroidPersianCalendar#156]
اذان صبح یا پخش نمیشود یا زمان پخش نادرست میباشد. این مورد روی دو گوشی نکسوس ۶پی و نکسوس ۵ امتحان شده و هردو دچار این مشکل است.

**Comment by ebraminio** [comment]
سلام جناب طاهری، تغییراتی که در نسخه‌های قبل داشتیم احتمال زیاد مشکل را بهبود داده است، حتماً بررسی کنید، ممنون :)
