### ISSUE TITLE
اشکال در تنظیم موقعیت مکانی

### ISSUE THREAD

**Issue by smtaheri** [ebraminio/DroidPersianCalendar#158]
برنامه هنگام تنظیم موقعیت جغرافیایی از طریق جی پی اس برای مکانهای ناموجود در فهرست برنامه دچار گیر شده و فورس کلوز میشود.

**Comment by behdad222** [comment]
من دیروز با نسخه ۵.۶.۰ تو گرفتن موقعیت از gps به کرش خوردم
تهران هم بودم
@ebraminio

**Comment by ebraminio** [comment]
من هیچ وقت مشکل نداشتم لاگی چیزی ندارید؟

**Comment by behdad222** [comment]
نه متاسفانه
حتی اشتباهی دستم خورد و ریپورت هم نشد

**Comment by ebraminio** [comment]
فکر می‌کنم در نسخهٔ جدید مشکل (با استفاده از اپلای به جای مشکل) برطرف شده باشد
