### ISSUE TITLE
عدم نمایش متن کامل یک رویداد بر روی موبایل

### ISSUE THREAD

**Issue by msharify** [ebraminio/DroidPersianCalendar#162]
با سلام . ممنون از برنامه خوبتون. این تقویم ، رویدادهایی که توضیحات طولانی دارن روی موبایل کامل مشخص نمیشه و سطرش یه جایی به پایان میرسه و یه سری کلمات ادامه اون سطر رو نشون نمیده و از سطر بعد رو ادامش توی همون سطر جدید مینویسه و یه سوال دیگه اینکه ورژن جدید این نرم افزار رو چگونه باید از اینجا دانلود کنم؟
ممنونم

**Comment by ebraminio** [comment]
مشکل برطرف شده در به روز رسانی بعدی در پلی و بازار خواهد آمد
