### ISSUE TITLE
مناسبت‌های اسلامی که در تقویم رسمی تعطیل نیست

### ISSUE THREAD

**Issue by mrhosseini** [ebraminio/DroidPersianCalendar#163]
سلام

ظاهرا در حال حاضر فقط آن دسته از مناسبت‌های اسلامی در برنامه وجود دارد که در تقویم رسمی تعطیل باشند. مثلا روز تولد حضرت زهرا (سلام الله علیها) که روز مادر هم هست (۲۰ ام جمادی الثانی) در حال حاضر در تقویم مشخص نیست 

خوب است که این مناسبت‌ها هم به برنامه اضافه شود و یا به صورت افزونه امکان اضافه کردن آن‌ها وجود داشته باشد.

**Comment by ebraminio** [comment]
بله به دلیل نبود الگوریتم مناسبت قمری #53 است که در صفحهٔ درباره نیز ذکر شده است
