### ISSUE TITLE
اشکال در دریافت مختصات از جی پی اس یا شبکه

### ISSUE THREAD

**Issue by AliMirlou** [ebraminio/DroidPersianCalendar#171]
در صورت ندادن دسترسی مکانی به برنامه در اندروید 7، هنگام دریافت مختصات، برنامه کرش می کند.

![bug](https://user-images.githubusercontent.com/19661419/30690960-34a76b78-9edb-11e7-8443-883804b9d927.jpg)

**Comment by ebraminio** [comment]
سلام! ممنون بابت لطفی که در اطلاع رسانی این مشکل به پروژه کردید :)
