### ISSUE TITLE
Qibla/Compass does not work in LineageOS 14.1

### ISSUE THREAD

**Issue by msadeqhe** [ebraminio/DroidPersianCalendar#177]
Hi, I am using LineageOS (Android version 7.1.2) on Galaxy Note 3 (SM-N9005) android phone. All features of your application is working flawlessly, except Qibla/Compass feature which does not work; arrows and directions are not moving!

I tried other Qibla/Compass Android applications, and they worked very well on my phone.

<p dir="rtl" align="right">سلام، من از LineageOS (Android version 7.1.2) روی گوشی اندروید Galaxy Note 3 (SM-N9005) استفاده می‌کنم. همه قابلیت‌های برنامه شما بی‌عیب کار می‌کند، بجز قابلیت قبله‌نما/قطب‌نما که کار نمی‌کند؛ نشانه‌ها و جهت‌ها حرکت نمی‌کنند!</p>

<p dir="rtl" align="right">من سایر برنامه‌های اندرویدی قبله‌نما/قطب‌نما را امتحان کردم، و آنها به خوبی روی گوشی من کار کردند.</p>

**Comment by ebraminio** [comment]
ممنون از توضیحات خوب و مفصلتان، واقعیت ایده‌ای ندارم، در کدام برنامه مشکل کمتری مشاهده کردید؟

**Comment by msadeqhe** [comment]
<p dir="rtl" align="right">بطور مثال برنامه (open source) اندرویدی قبله‌نما/قطب‌نمای زیر بر روی گوشی من کار می‌کند:</p>

[Prayer Times (Namaz Vakti)](https://play.google.com/store/apps/details?id=com.metinkale.prayer)
[Prayer Times (Namaz Vakti)'s source code](https://github.com/metinkale38/namaz-vakti-android)

<p dir="rtl" align="right">بخش قبله‌نما/قطب‌نمای برنامه شما (DroidPersianCalendar) نیز قبلا بر روی گوشی من کار می‌کرد، اما از زمانیکه سیستم عامل گوشی‌ام را به LineageOS 14.1 (Android 7.1.2) تغییر دادم، از کار افتاد.</p>

<p dir="rtl" align="right">با تشکر از پاسخ شما.</p>

**Comment by ebraminio** [comment]
<div dir="rtl" align="right">
ممنون از پیگیرتون، اینکه برنامه‌ای متن‌باز دیگه‌ای رو مقایسه کردید خیلی خیلی مفید هست

https://github.com/metinkale38/prayer-times-android/blob/master/app/src/play/java/com/metinkale/prayerapp/compass/FragMap.java#L117

این برنامه مختصات را از سرویس گوگل می‌گیرد که از جی‌پی‌اس هم می‌تواند استفاده کند که بسیار مطمئن‌تر است و احتمالاً ما نیز باید چنین کنیم، در گذشته مشکلی با کتابخانه‌های گوگل داشتیم که احتمالاً نیاز است در رابطه با استفاده از آن بازنگری کنیم.

ولی حدسم این است LineageOS مشکلی با به‌روزرسانی‌شان ایجاد کرده‌اند.

اگه برنامهٔ دیگر متن‌باز دیگه‌ای رو هم تونستید مقایسه کنید هم عالی می‌شود که با اطمینان بتوانم بگویم مشکل از LineageOS است یا تقویم. ممنون
</div>

**Comment by msadeqhe** [comment]
<p dir="rtl" align="right">برنامه قبله‌نمای متن‌باز زیر نیز بدون مشکل بر روی LineageOS کار می‌کند:</p>

[Muslim Companion - Kaaba Salat](https://play.google.com/store/apps/details?id=net.gahfy.muslimcompanion)
[Muslim Companion - Kaaba Salat's source code](https://github.com/gahfy/muslim-companion)

<p dir="rtl">با تشکر.</p>

**Comment by ebraminio** [comment]
https://github.com/gahfy/muslim-companion/blob/master/app/src/main/java/net/gahfy/muslimcompanion/fragment/CompassFragment.java

این مورد بر خلاف قبلی ظاهرا از رابطی مشابه با برنامه تقویم کار می‌کند و احتمالا با مشابه کردن تقویم با پیاده‌سازی آن بتوان مشکل را در سیستم‌عامل‌تلن بهبود داد

**Comment by msadeqhe** [comment]
<p dir="rtl" align="right">سلام. ممنون که پیاده‌سازی برنامه‌های متن‌باز مشابه را بررسی کردید.<p>

<p dir="rtl" align="right">من بیشتر تحقیق کردم و به نظر می‌رسد مشکلی که برای من بوجود آمده، مشابه مشکلی است که در این صفحه مورد بررسی قرار گرفته است:</p>

[Compass not working on Galaxy S3/LineageOS 14.1](https://github.com/mvglasow/satstat/issues/122)

<p dir="rtl" align="right">با توجه به پیام‌های رد و بدل شده در صفحه مذکور، مشکل در استفاده از TYPE_ORIENTATION است که از API Level 8 به بعد در سیستم عامل اندروید منسوخ (deprecated) شده است.</p>

<p dir="rtl" align="right">و با توجه به ایراد (bug) گزارش شده در این صفحه:</p>

[Compass only works in a limited number of applications](https://jira.lineageos.org/plugins/servlet/mobile#issue/BUGBASH-1010)

<p dir="rtl" align="right">احتمالا مشکل در عدم پشتیبانی LineageOS 14.1 از TYPE_ORIENTATION بخاطر منسوخ (deprecated) بودن آن است. اگر اینطور باشد (که بنظر می‌رسد)، راه حل استفاده از API جدید اندروید است و یا باید توسعه‌دهندگان LineageOS به ادامه پشتیبانی از API قدیمی که منسوخ شده است، تن بدهند! بهرحال در آینده احتمال عدم پشتیبانی سایر توسعه‌دهندگان توزیع اندروید (شامل سامسونگ، سونی و غیره) از API منسوخ شده نیز ممکن است.</p>

**Comment by msadeqhe** [comment]
<p dir="rtl" align="right">می‌توان در برنامه تقویم فارسی بررسی کرد که اگر API منسوخ شده پشتیبانی می‌شد از آن برای تعیین جهت قبله‌نما/قطب‌نما استفاده شود و در غیر اینصورت، از API جدید استفاده شود.</p>

**Comment by ebraminio** [comment]
<div dir="rtl" lang="fa">
عالی‌ست. این مقبوح بودن رابط برنامه‌نویسی مذکور از همان اول در ذهن من بود ولی ظاهراً چاره‌ای برای آن نداشتم دقیقاً به خاطر نمی‌آورم.

عالی است می‌توانیم ببینیم نتیجه بحث‌های آن پروژه‌ها چگونه خواهد بود، اگر ممکن آن بحث‌ها را پیگیر باشید و ما را مطلع کنید. پروژهٔ LineageOS هم پروژهٔ جالبی بود ولی از آنجایی که مدتی است گوشی اندرویدی ندارم توانایی آزمایش آن را ندارم.
</div>

**Comment by danialbehzadi** [comment]
‫برای من هم کار نمی‌کرد. ولی الآن کار می‌کنه در LOS14.1. می‌شه دوباره امتحان کنید؟

**Comment by msadeqhe** [comment]
ممنون که اطلاع دادید. بله، برای من هم به درستی کار می‌کند.

**Comment by ebraminio** [comment]
<div dir="rtl">
با تشکر از هر دو گرامی پس بهتر است آن را تغییر ندهیم.
</div>
