### ISSUE TITLE
نمایش فرم یادداشت روز جداگانه؛ بجز یادآور خود گوشی

### ISSUE THREAD

**Issue by BeginnerTensorflow** [ebraminio/DroidPersianCalendar#178]
سلام. ممنون واقعا عالی نوشته شده.
فقط یک مورد من می خواستم بدونم کدوم بخش از کدها می شود تنظیم کرد که مثلا بجای اینکه یادآور گوشی را نمایش دهد و کاربر یادداشت ها و یادآوری هایش را ثبت کند؛ بیاید و activity مربوط به خود ما را نمایش دهد که مثلا به صورت putextra تاریخ را به آن صفحه ارسال کنیم که بتوانیم یادداشت و یادآور مورددلخواه خود را طراحی کنیم

ممنون و سپاس گذار

**Comment by ebraminio** [comment]
سلام، تقویم قابلیت یادداشت و ذخیره اطلاعات درون خود ندارد و به نظر کار زیادی نمی‌شود اینجا کرد، ممنون
