### ISSUE TITLE
پیشنهاد برای ویجت

### ISSUE THREAD

**Issue by A-Shahbazi** [ebraminio/DroidPersianCalendar#179]
یکی از قابلیت‌های بسیار کاربردی در برنامه‌های تقویم غیر متن باز نمایش اوقات شرعی، مکان انتخاب شده توسط کاربر و مناسبت‌های روز توی ویجت هست. به نظرم اضافه شدن این موارد به ویجت(و یا اضافه کردن ویجتی که این اطلاعات رو هم داشته باشه) خیلی خوبه

برای مثال میشه به تقویم بادصبا اشاره کرد
http://www.badesaba.ir/
https://cafebazaar.ir/app/com.mobiliha.badesaba/?l=fa

**Comment by ebraminio** [comment]
درست می‌فرمایید و حل سختی ندارد، باید مشکل را در انتشارهای اخیر برطرف می‌کردیم :/

**Comment by ebraminio** [comment]
در نسخهٔ بعد مکان هم در ویجت ۲در۲ نمایش خواهد داده شد :)
