### ISSUE TITLE
نمایش چپ به راست در گوشی

### ISSUE THREAD

**Issue by greyzero** [ebraminio/DroidPersianCalendar#182]
سلام و تشکر از کار بسیار خوبتون
نمایش تقویم در نوتیفیکیشن بار و صفحه ی لاک اسکرین به صورت چپ به راست نمایش داده می شود  
اگر امکانش هست اون رو راست به چپ و با فونت بزرگ تر کنید عالی می شه.
ممنون

**Comment by kshirazy** [comment]
بله،ممنون وتشکرفراوان؛
خسته نباشید؛

**Comment by ebraminio** [comment]
<div dir="rtl">
از آنجایی که تقویم از نوتیفیکیشن اصلی گوشی استفاده می‌کند در هر نسخه و دستگاهی شکل آن به شکلی خواهد بود. در گوشی‌های کمتر تغییریافته گوگلی مانند نکسوز معمولاً نوتیفیکیشن به شکل درستی راست به چپ نمایش داده می‌شود ولی در گوشی‌های سامسونگ دیده‌ام که اینگونه نیست. راه حل چندانی برای حل این مسأله به ذهنم نمی‌رسد به جز اینکه از نوتیفیکیشن شخصی‌سازی شده استفاده شود که چندان مطلوب نیست ولی فکر می‌کنم در به روزرسانی دستگاه به نسخه‌های بعد این مشکل کم کم برطرف می‌شود
</div>

**Comment by greyzero** [comment]
ممنون از پاسختون.
تقویم های دیگه مثل باد صبا الان داره درست نمایش می ده. گوشی من سامسونگ گالکسی اس 8 پلاس هستش.
با این حال بازم ممنون. بابت کار خوبتون. چون ساده و سبک و کارار هست.
اگر بشه فونتش رو هم در نمایش تقویم کمی بزرگتر نمایش داد یا ویدجتش رو هم با فونت بزرگ تر نمایش داد کاربردی تر و عالی هستش.

**Comment by ebraminio** [comment]
<div dir="rtl">
برنامه‌های دیگر از نوتیفیکیشن شخصی‌سازی شده استفاده می‌کنند. راستی یک راه حل دیگر این هست که زبان گوشی را فارسی کنید به این ترتیب نوتیفیکیشن‌هایش نیز در سامسونگ راست به چپ می‌شوند. دربارهٔ اندازه زمانی آن را انجام داده بودم ولی به دلایلی حذف شد احتمالاً باید دوباره آن را پیاده‌سازی کنیم.
</div>

**Comment by greyzero** [comment]
باز هم تشکر.

**Comment by ebraminio** [comment]
در نسخهٔ ۵.۵.۱ در همه گوشی‌ها اصلاح مربوط به راست به چپ قرار داده شده ولی به دلیل مشکلات با بعضی از گوشی‌ها 
اصلاح به نسخه‌های بعد از اندروید ان محدود شد. تقریباً می‌شود گفت این نهایت کاری است که برایمان ممکن است و به همین دلیل مشکل را می‌بندم

نسخهٔ بتا جدید را می‌توانید در https://play.google.com/apps/testing/com.byagowi.persiancalendar آزمایش کنید.

ممنون از همفکری شما دوست گرامی :)

**Comment by greyzero** [comment]
تشکر فراوان
