### ISSUE TITLE
مصرف زیاد رم و فعال بودن همیشگی پردازنده

### ISSUE THREAD

**Issue by OmidHekayati** [ebraminio/DroidPersianCalendar#183]
درود
ممنون بابت تقویم خوبتون. راستش من تا قبل از این داشتم از بادصبا استفاه می کردم ولی خوب به دلایل مشکلات فراوانی که داره به اپ شما برخورد کردم.
اما یک مشکل اساسی که داره این هست همیشه مقدار زیادی رم حداقل 40 مگ در حال مصرف هست و در بخش دولوپرز هم همیشه یک پروسس فعال برای اپ وجود داره.
خیلی اندروید کد نزدم ولی خوب می دونم یکجای کار اشکال داره که این مصارف اضافی وجود داره. اینجوری خیلی مصرف باتری بالا میره. چون همانطور که می دونید ساختار رم به نحوی هست که برای نگهداری اطلاعات نیاز به شارژ الکتریسیته داره که در گوشی باعث ایجاد مشکل می کنه.

**Comment by ebraminio** [comment]
سلام، مصرف رم برنامه تاجایی که می‌دونم کمترین حد ممکن هست چون پروفایل‌ها حافظه روی قسمت‌های مختلفش انجام شده، پروسس فعال هم حداقل برای به روز کردن عدد بالا نیاز هست و کار خاصی تاجایی که می‌دونم نمی‌شود در رابطه باهاش انجام داد.

**Comment by OmidHekayati** [comment]
البته قصد ایراد گرفتن نیست ولی بعید می دونم این حالت های بهینه باشه!! الان واتس اپ که یک اپ با نیاز به یکسری فرآیندها خاص هم می باشد مصرف پروسس را فقط در حد باز بودن اپ استفاده می کنه و در بقیه مواقع کلا کش میشه پروسس. البته این مشکل فعال بودن دائمی را اپ هایی مثل تلگرام، اینستاگرام، فیسبوک، ... هم دارن که باعث مصرف بسیار الکی باتری میشن.
در مورد مصرف رم هم بنظرم در حالت استندبای واقعا 1 مگ رم هم زیاد هست!!

**Comment by ebraminio** [comment]
حالت بهینهٔ مطلق که نه ولی یک حالت قابل تحمل نسبی با امکانات محدود هست مثلاً اگه کتابخونه‌های ساپورت گوگل از  برنامه  برداشته بشن خب حجم برنامه و رمی که مصرف می‌کنه احتمالاً کمتر می‌شه ولی خیلی از امکانات از دست می‌ره، اگه کل برنامه با سی نوشته بشه بهینه‌ترین حالت می‌شه ولی قابل حمل بودن از دست می‌ره، برنامه‌ها هم معمولاً با یه تعادلی نوشته می‌شود که در تعادلی که مد نظر داشتن (زبان، کتابخونه‌ها و اندازه) قضاوت و بررسی می‌شن، اگر فرصت داشتید می‌توانید با پروفایلر حافظه اندروید استودیو یک نگاهی به برنامه بندازید اگه موردی دیدید که قابل بهینه‌سازی حتماً مطلع کنید، ممنون

**Comment by ebraminio** [comment]
یک نکته‌ای که یادم اومد در پروفایلر خواهید دید حافظه‌ای که سیستم عامل به برنامه اختصاص داده و حافظه‌ای که برنامه واقعاً در حال استفاده دارد، مثلاً تاجایی که یادمه برنامه بدون اینکه اپ آن باز شود ۶مگ بود وقتی که صفحهٔ اصلی می‌آمد  ۱۵ مگ ولی در کل از سیستم‌عامل ۴۰ مگ گرفته شده

**Comment by behdad222** [comment]
این میزان مصرف رم بستگی زیادی به گوشی هم داره
تو گوشی من hello word به تنهایی حدود ۳۰ مگ رم میگیره
تو گوشی مادر بزرگم ۷ مگ

ولی شاید بشه همونطور که شما گفتید تو بک‌گراند یه کارهایی کرد که کمتر مصرف کنه باید بررسی کنم

در مورد دوم هم شاید با api های جدید اندروید بشه کاری کرد که یه سرویس در بک‌گراند ترد باز نباشه برای همیشه.
این رو هم سعی میکنم بررسی کنم در اولین فرصت

همینطور در نسخه‌های جدید اندروید امکانی ایجاد شده که بتونید بررسی کنید هر اپ چقدر باتری مصرف کرده
با بررسی این قسمت متوجه میشید که مصرف باتری اپ بسیار بسیار کم هست

ممنون از توجه و نظرات شما

@OmidHekayati
