### ISSUE TITLE
F-Droid build for 5.4.0 fails

### ISSUE THREAD

**Issue by danialbehzadi** [ebraminio/DroidPersianCalendar#186]
F-Droid build for 5.4.0 fails because it could not find com.android.tools.build:gradle:3.0.1

Here is the log: https://f-droid.org/wiki/page/com.byagowi.persiancalendar/lastbuild

**Comment by ebraminio** [comment]
<div dir="rtl" lang="fa"'>
به نظرم مشکل از آن طرف باشد، من ایمیل هم زدم، می‌توانید در باگ ترکر آن‌ها هم درخواست دهید؟
</div>

**Comment by danialbehzadi** [comment]
‫فکر می‌کنم مشکل از خط ۹ پروندهٔ `build.gradle` باشه.

**Comment by behdad222** [comment]
@ebraminio همون خط رو آپدیت کنیم و یه ورژن بدیم برای fdroid?

**Comment by ebraminio** [comment]
اوکی هست فقط سی‌آی خراب نشه

**Comment by abbas-oveissi** [comment]
@behdad222 @ebraminio 
<p dir="rtl">
فکرکنم توی سورس fdroid ریپوهای google به build.gradle اپ (top-level) اضافه نشده و همین قضیه باعث شده که نتونه پلاگین نسخه‌ی سه رو پیدا کنه</p>

**Comment by ebraminio** [comment]
در اینجا پرسیدم که مشکل چیست
https://gitlab.com/fdroid/fdroiddata/issues/1249

**Comment by ebraminio** [comment]
چند روز پیش اطلاع دادند که مشکل برطرف شده است :)
