### ISSUE TITLE
اقا تاریخا بهم ریخته

### ISSUE THREAD

**Issue by coolheaded73** [ebraminio/DroidPersianCalendar#187]
یک روز قمری تاریخو جلو نشون میده نرم افزار

**Comment by coolheaded73** [comment]
اگر مناسبت های جلالی رو هم اضافه کنی که عالی میشه

**Comment by ebraminio** [comment]
سلام! در رابطه با تقویم قمری، #53 

مناسبت‌های بیشتر رو می‌کنیم در نسخهٔ جدید، موفق باشید :)
