### ISSUE TITLE
اضافه کردن شیفت کاری 

### ISSUE THREAD

**Issue by salametak** [ebraminio/DroidPersianCalendar#194]
با سلام اگه شیفت کاری هم به تقویم تون اضافه کنید دیگه بی نظیر میشه بنده خودم بصورت شیفتی سرکارم ۱۲ ساعت ۴ روز روزگار و ۴ روز شب کار و ۴ روز بیکار ساعتی هم اضافه کار میاییم اگه این قابلیت ها اضافه بشه به تقویم عالی میشه

**Comment by ebraminio** [comment]
<div dir="rtl">
سلام! ممنون ایدهٔ خیلی جالبیه، در یه برنامهٔ دیگه با react-native یا همین برنامه اصلاً، قسمتی ایجاد شه که انواع شیفت‌ها کاری رو لیست کنیم و کاربر بتونه از بینشون اونی که نیاز داره رو انتخاب کنه و تا چند روز برنامه‌ریزی کنه که دستگاه مطلعش کنه یا جایی براش لیست کنه
</div>

**Comment by salametak** [comment]
دادش واسه این کار مایه سیکل کاری رو میدیم به برنامه شیفت روز و شب و بیکاری
رو بعدش خودش تکرار کنه تا هر تاریخی که بخواهیم و ثبت کنیم تو قالب تقویم
خیلی بهتره

**Comment by behdad222** [comment]
میشه بیشتر توضیح بدید چه کاربردی داره
@salametak

**Comment by salametak** [comment]
الان تمامی کارکنان اکثر شرکت ها نیروهاشون بصورت شیفتی کار میکنن ۶ساعته یا ۸
ساعته و یا مثل خودم ۱۲ ساعته شیفت هستم بدین صورت که ۴ روز میشم روز کار و ۴
روز شب کار و ۴ روز شب کار این قابلیت رو تقویم persian calender در سیستم
عامل ios داراست بنده یه سیکل کامل رو دادم بهش و خودکار تا آخر سال معلوم بود
روز کار کی هستم و چه موقع و چه تاریخی بیکار یا شب کارم یه سیکل کاری یعنی
تعداد روز های روز کاری رو وارد کردم و بعدش شب کاریم و بعد بیکاری بعد وقتی
تقویم بصورت ماهانه نمایش میداد کامل مشخص بود شما میتونی روزکاری رو زرد رنگ
و شب کاری رو آبی رنگ و بی کاری رو بیرنگ یا سفید باشه

**Comment by ebraminio** [comment]
سلام این قابلیت پیاده‌سازی شده فقط مونده جزئیات آن که تا انتشار نسخهٔ بعدی امیدوارم نهایی شود، ممنون :)
