### ISSUE TITLE
تعطیلات مذهبی سال ۹۷ اعمال نشده

### ISSUE THREAD

**Issue by Hitaro** [ebraminio/DroidPersianCalendar#199]
مثلا ۱۶ خرداد ۹۷ که تعطیله، در تقویم اعمال نشده؛ یا ماه‌های قبل‌ترش که بعثت و نیمه‌شعبان در تقویم نیست. چون این تعطیلات، رسمی حساب می‌شن، قاعدتاً باید مثل تعطیلی ۱۵ خرداد، اعمال بشن. ممنون

![Khordad96](https://u.teknik.io/OWPw2.png)

**Comment by mehdisamavat** [comment]
events.json
همه ی رویدادهای مربوط به فایل بالا میباشد برای من دقیقا در تاریخی که ذکر کردید تعطیل  است --داخل فایل جیسون بالا دنبال تاریخ مد نظرتون بگردید اگر متغییر تعطیلات ترو نبود فایل جیسون رو اپدیت کنید

**Comment by ebraminio** [comment]
سلام نسخهٔ سال جدید را باید نصب کنید، تاجایی که یادم هست برنامه در صورت نداشتن مناسبت‌های سال جدید یک هشداری می‌دهد که نیاز است نسخه جدید را نصب کنید، از آنجایی که تقویم قمری دقیق نیست #1 و این برنامه دسترسی اینترنت نمی‌گیرد که بخواهد به صورت آنلاین آن را به روز کند راه حل دیگری برای مشکل به نظرم نمی‌رسد به خاطر همین این ایشو را می‌بندم، با احترام
