### ISSUE TITLE
getDayOfYear()کار نکردن متد 

### ISSUE THREAD

**Issue by mehdisamavat** [ebraminio/DroidPersianCalendar#200]
سلام دوستان متد
 `getDayOfYear()`
فورس کلوز میده و اکسپشن زیر رو اجرا میکنه
` public int getDayOfYear() {
        throw new RuntimeException(Constants.NOT_IMPLEMENTED_YET);
    }
`

**Comment by runo280** [comment]
سلام، همونطور که نوشتن هنوز پیاده سازی نشده این متد

**Comment by ebraminio** [comment]
واقعیت این قسمت از پروژه همانطور که در قسمت «درباره» نوشته شده از برنامهٔ تقویم دیگری گرفته شده و تا وقتی که در این پروژه قرار نیست استفاده بعید است مجال اصلاح آن وجود داشته باشد
