### ISSUE TITLE
نسخه داخل اف‌دروید عقب‌تر از نسخه گوگل‌پلی

### ISSUE THREAD

**Issue by onrea** [ebraminio/DroidPersianCalendar#201]
Latest Version in F-Droid: 5.3.1 (24/09/2017)
Latest Version in Google Play Store: 5.4 (20/12/2017)

**Comment by ebraminio** [comment]
گزارش شده در #186

بدشانسی بوده من برایشان ایمیل هم زدم و پاسخی دریافت نکردم اگر می‌خواهید آن‌ها را نیز مطلع کنید، امیدوارم با انتشار بعد مشکل برطرف شود.
