### ISSUE TITLE
وصل شدن به تقویم گوگل و فیسبوک

### ISSUE THREAD

**Issue by amirrezaeng** [ebraminio/DroidPersianCalendar#212]
سلام
بازم از تقویم خوبتون ممنونم. یک ویژگی خوبی که تقویم خدابیامرز سان کلندر داشت این بود که به گوگل 
 فیسبوک وصل می‌شد و تاریخ تولد دوستان رو هم در برنامه و هم در ویجت نشون می‌داد. به نظرم اضافه کردن این ویژگی خیلی مفیده.
ممنون

**Comment by ebraminio** [comment]
به این دلیل که نیازمند دسترسی بود در طراحی اولیه برنامه این موضوع در نظر گرفته نشد ولی در ادامه برنامه‌ای جهت افزودن آن وجود دارد. ممنون از شما :)

**Comment by ebraminio** [comment]
در نسخهٔ بعد از مناسبت‌های گوشی استفاده خواهد کرد :)

**Comment by ebraminio** [comment]
البته کاربر باید آن را فعال کند
