### ISSUE TITLE
سلام.

### ISSUE THREAD

**Issue by mhdisharifi** [ebraminio/DroidPersianCalendar#220]
تو اندروید نسخه‌ی ۶.۰ ویجت برنامه در نوتیفیکیشن بار با فونت مشکی نمایش داده می‌شه و مشاهده رو برای کاربر مشکل می‌کنه. نسخه‌ی قبل از تاریخ ۸ تیرماه بدون مشکل بود.

**Comment by ebraminio** [comment]
ممنون از اینکه اینجا اطلاع دادید، مشکل از تلاشی بود که سعی می‌کردم برای گوشی‌های بیشتری نوتیفیکیشن را راست‌چین و کنم، در نسخهٔ بعد این مشکل را برطرف می‌کنم

**Comment by mhdisharifi** [comment]
ممنون از توجه‌تون ، چون بهترین تقویم فارسی‌ای هست که من چندساله استفاده می‌کنم برام مهم بود.
خسته نباشید.

**Comment by ebraminio** [comment]
اصلاح در نسخهٔ بتا https://play.google.com/apps/testing/com.byagowi.persiancalendar قرار داده شد. 

با تشکر :)

**Comment by mhdisharifi** [comment]
سلام. بله نصب کردم و درست شده بود. خسته نباشید.
و همینطور اینکه باعث افتخاره که بتا تستر برنامه‌ی به این خوبی شدم. ممنونم.
راستش موضوع دیگه‌ای که می‌خواستم در مورد برنامه مطرح کنم این بود که قبلاً تا جایی که خاطرم هست فونت‌ها کمی ریزتر بودن و تقویم و مناسبت‌ها به همراه تاریخ میلادی و قمری اون تاریخی که انتخاب می‌کردم ، همگی بدون نیاز به اسکرول کردن قابل مشاهده بوده و از این نظر رابط کاربری جذاب‌تری رو در اختیار کاربر قرار میداد. شاید اگه بصورت پیش‌فرض به همون شکل قبلی باشه و امکان بزرگنمایی رو از طریق تنظیمات به کاربر بده تجربه‌ی استفاده‌ی مطلوب‌تری رو برای کاربر بوجود میاره. این آپشن هم که در مورد انتخاب نوع مناسبت‌ها قرار دادید فوق‌العاده ایده‌ی خوبی هستش. خسته نباشید.

**Comment by ebraminio** [comment]
اگه به غیر از نسخهٔ مربوط به ۴ ۵ سال مد نظرتون هست که والا یادم نمی‌آید تغییری در این چندسال داده باشیم ولی در طراحی نسخهٔ استفاده بهینه‌تر از فضاها را بیشتر در نظر می‌گیریم، اگر مشکل دیگری داشتید فایل دیگری در گیت‌هاب باز کنید (هر چند مشکلی که داشته باشید) هم عالی است :) ممنون
