### ISSUE TITLE
افزودن اذان‌های بیشتر

### ISSUE THREAD

**Issue by zokayi** [ebraminio/DroidPersianCalendar#221]
سلام. ممنون از برنامه خوب و مفیدتون
اپلیکیشن تون در کل بی‌نقصه، فقط اگه یه کم تغییرات کوچیک برا کامل‌تر کردن شاید بهتر باشه، مثلا اذان‌های بیشتری  اضافه بشه، در ضمن، آیکون میانبر قسمت نوار اعلانات شاید در حالت روشن خوشکلتر باشه، مثل وقتی که وای‌فای یا بلوتوث روشنه

**Comment by ebraminio** [comment]
ممنون از شما، عالی :)

**Comment by ebraminio** [comment]
مشکل میانبر حل شد :) این باگ را فقط به افزودن اذان‌ها اختصاص می‌دهیم

**Comment by ebraminio** [comment]
واقعیت، مشکل اصلی با اذان با صداهای بیشتر و بهتر نداشتن مجوز حق تکثیر برای اذانی آزاد قابل استفاده در برنامهٔ آزاد است

**Comment by ebraminio** [comment]
ادغام در #157 که موضوعی مشابه دارد
