### ISSUE TITLE
تاریخ قمری و میلادی

### ISSUE THREAD

**Issue by fcbwin** [ebraminio/DroidPersianCalendar#230]
سلام. تاریخ قمری و میلادی رو با قابلیت انتخاب خود کاربر در ویجت برنامه بگنجانید

**Comment by ebraminio** [comment]
کمی سخت است به این دلیل که تقویم اصلی هم قابل عوض شدن است، احتمالاً ولی آنچیزی که می‌خواستید ممکن شده پس این فایل را می‌بندم، ممنون :)
