### ISSUE TITLE
مرجعیت events.json

### ISSUE THREAD

**Issue by mehrdaad** [ebraminio/DroidPersianCalendar#232]
ممنون از تلاشتون.
یک سوالی داشتم ممنون میشم کمی شفاف سازی بکنید.
ظاهرا تمام مناسبت های میلادی، شمسی و غیره رو تو فایل https://github.com/ebraminio/DroidPersianCalendar/blob/master/PersianCalendar/src/main/res/raw/events.json نگه داری میکنید.
آیا این فایل نیاز به به روز رسانی مرتب دارد یا نه؟
و اینکه اگه بخایم این فایل رو تو یه سرویسی دیگه استفاده کنیم چقدر این فایل قابل اطمینان هست و مرجعیت داره؟
خیلی ممنون

**Comment by ebraminio** [comment]
بله بعضی از مناسبت‌ها نیاز به به‌روزررسانی دارد. واقعیت مثل باقی پروژه نه اطمینانی نیست ولی خب اگه بررسی کنید و اشکالی دیدید ممنون می‌شیم ما رو هم مطلع کنید و لطفاً اون پروژه رو هم اوپن‌سورس بذارید :)

**Comment by mehrdaad** [comment]
بله اپن سورسش کردم. 
https://github.com/mehrdaad/react-native-calendars/tree/moment
لایبرری کلندر برای ری اکت نیتیو

میخاستم از این فایل جی‌سان استفاده کنم برای نمایش مناسبت ها. اگه مورد خاصی هست که بشه بررسی کرد و این فایل رو به روز رسانی کرد خوشحال میشم کمک کنم.
از حرفاتون اینجوری استنباط کردم که میتونم استفاده کنم برای پروداکشن خلاصه:)

**Comment by ebraminio** [comment]
جالب بود، عالی :) برای مثال این دو

https://github.com/ebraminio/DroidPersianCalendar/blob/master/PersianCalendar/src/main/res/raw/events.json#L949-L953

نیاز هست هر سال چک شوند و یکی تعطیلی رسمی هم نیز هست که آن را مهم‌تر نیز می‌کند

**Comment by mehrdaad** [comment]
متوجه شدم. تمام تعطیلی‌های مناسبتی که از تقویم قمری میاد هر سال باید تبدیل بشه.
شاید بشه یه لایبریری نوشت که به ازای هر سال همه اینا رو محاسبه کنه و یه فایل جی‌سان بسازه.

**Comment by ebraminio** [comment]
تمامش که نه البته ولی خب

**Comment by ebraminio** [comment]
بعد قوانین ایران هم خودش تعطیلی‌های جدید اضافه یا حذف کرد، این موارد هم پیش اومده تا حالا که نیاز با پی‌دی‌اف انتشاری بررسی بشه

**Comment by mehrdaad** [comment]
بله درسته. به هر روی به نظرم همین فایل جی‌سان یه نقطه شروع خیلی خوبی هست. 
مرسی از شما :)
