### ISSUE TITLE
راهنمائی برای توسعه

### ISSUE THREAD

**Issue by best200** [ebraminio/DroidPersianCalendar#233]
درود استادان ارجمند
 لطفا در مورد توسعه این پروژه توضیح کامل دهید چون مبتدی هستم. ضمنا ورژن اندروید استودیو من 3.1.3 می باشد
با سپاس

**Comment by ebraminio** [comment]
سلام! اگر برنامه را با اندروید استودیو باز کنید و مشکل اینترنت نداشته باشید کار دیگری تقریباً لازم نیست انجام دهید. طبق جی‌پی‌ال، مجوزی که از یک قسمت کد که از پروژه‌ای دیگر وارد شده‌است، مجوز تقویم فقط استفاده از آن را در پروژه‌ای متن‌باز دیگر (که مانند همین پروژه سورس آن منتشر شده باشد) را می‌دهد، مراقب باشید از سورس‌های آن در برنامه‌ای غیرمتن‌باز استفاده نکنید :) موفق باشید
