### ISSUE TITLE
باگ ورژن 5.6.0

### ISSUE THREAD

**Issue by Azadfar2009** [ebraminio/DroidPersianCalendar#234]
با عرض سلام و خسته نباشید،
مشکل در ندیدن تعطیلی ها بود ک در قسمت تنظیمات، تعطیلی های ابران اضافه شد و مشکل برطرف شد، با تشکر

**Comment by ebraminio** [comment]
سلام! در نسخهٔ جدید تعطیلی‌ها ایران به هر حال فعال می‌شوند و اگر کاربر قبلاً تنظیمات را مشاهده نکرده باشد یک حالت اطلاع برای تنظیم مناسبت‌ها نیز داده می‌شود. ممنون :)
