### ISSUE TITLE
ویجت

### ISSUE THREAD

**Issue by fcbwin** [ebraminio/DroidPersianCalendar#236]
سلام. ممنون که تاریخ قمری و میلادی رو در ویجت اضافه کردید. فقط امیدوار بودم مناسبت ها رو هم همزمان با تاریخ شمسی قمری و میلادی یکجا داشته باشم در قسمت ویجت برنامه

**Comment by ebraminio** [comment]
ویجت ۲در۲ در نسخهٔ بعد :)
