### ISSUE TITLE
فرمت 

### ISSUE THREAD

**Issue by samanemzf** [ebraminio/DroidPersianCalendar#247]
سلام.من سالهاست این اپلیکیشن رو استفاده میکنم.ولی چون جدیدا نیاز به تقویم انگلیسی پیدا کردم متوجه این مشکل شدم.
به چه دلیل ماههای انگلیسی رو با اسامی فارسی گذاشتین؟اوت،ژوئیه و.... دیگر اسمهای فارسی باعث شده این برنامه زمانی که با تقویم انگلیسی کار داریم بلا استفاده و آزار دهنده باشه.چون تازه باید منبعی سرچ کنیم که بفهمیم منظور از اوت چیست؟ ژوئیه کدام است.این باگ بسیااااار آزار دهنده است

**Comment by ebraminio** [comment]
سلام. به این دلیل که تقویم رسمی کشور بر اساس آن است. از نسخهٔ آخر، آخرین گزینهٔ زبان‌ها را انتخاب کنید، احتمالاً همانی خواهد بود که مد نظرتان است، کاملاً انگلیسی و می‌توانید تقویم اصلی برنامه را نیز عوض کنید، موفق باشید :)
