### ISSUE TITLE
lock screen

### ISSUE THREAD

**Issue by fcbwin** [ebraminio/DroidPersianCalendar#256]
اگر امکانش هست قابلیت نمایش ساعت و سه تاریخ شمسی قمری میلادی و حتی مناسبت های روز یعنی همون چیزی که تو ویجت برنامه نمایش داده میشه در محافظ صفحه گوشی، هنگامی که صفحه قفله نمایش داده بشه.

**Comment by ebraminio** [comment]
اگه اندروید ۷ به بعد داشته باشید این مهم ممکن شده است، بررسی فرمایید :)
