### ISSUE TITLE
تقویم تاریخ

### ISSUE THREAD

**Issue by fcbwin** [ebraminio/DroidPersianCalendar#257]
در صورت امکان تقویم تاریخ رو به ویجت برنامه اضافه کنید. یعنی اینکه در ویجت بزنه مثلا 700 سال پیش در چنین روزی چه اتفاقاتی افتاده. البته فعال کردن این گزینه به انتخاب کاربر و حتی با هزینه باشه. ولی یه چیز کاملی باشه که تاحالا مثلش نیومده. چون ندیدم تقویم تاریخ کاملی رو موبایل. یدونه هست تا صد سال قبل رو فقط میگه

**Comment by ebraminio** [comment]
سلام! اگه ویجت ۲در۲ رو فعال کنید مناسبت‌های روز رو می‌گه و اگه تو خود تقویم خواندن از تقویم شخصی رو فعال کنید و تو تقویم گوگلتون یه لینک پیدا کنید که شامل مناسبت‌های تاریخی باشه ویجت هم اون رو نشون می‌ده، نگاهی بیندازید :)

مثلاً یک نمونه اینجاست
http://www.asrepayesh.com/content/617

https://calendar.google.com/calendar/ical/e7socanmf5mjmp7kkdgv85qhu8%40group.calendar.google.com/public/basic.ics

https://calendar.google.com/calendar/ical/0ln620itbaalaa1am3khmj5rug%40group.calendar.google.com/public/basic.ics

اگه خودتون هم درست کنید می‌تونید تو اینترنت منتشر کنید و دیگران استفاده کنند و در کل کار جالبی می‌شه :)
