### ISSUE TITLE
رویدادهای شخصی تکرارشونده

### ISSUE THREAD

**Issue by hadiceberg** [ebraminio/DroidPersianCalendar#270]
رویدادهای شخصی تکرار شونده که از تقویم گوگل وارد شده‌اند، نمایش داده نمی‌شوند. فقط اولین نسخه رویداد نمایش داده می‌شود.

**Comment by ebraminio** [comment]
درست می‌فرمایید فقط تکرار شونده در سال اجرا شده‌اند و باقی نه

**Comment by ebraminio** [comment]
انجام شد، در نسخهٔ بعد دیده می‌شود :)
