### ISSUE TITLE
مشکل تبدیل تاریخ شمسی به میلادی تو آپدیت جدید

### ISSUE THREAD

**Issue by aysha319** [ebraminio/DroidPersianCalendar#288]
سلام
persianToCivil 
تبدیل این تابع مشکل داره
تاریخ میلادی رو یکسال کمتر میده
قبل آپدیت درست کار میکرد
civilToPersian 
مشکلی نداره
بقیه رو چک نکردم
اگر بررسی کنین ممنون میشم

**Comment by ebraminio** [comment]
داخل برنامه هم می‌شه این مشکل رو دید؟

**Comment by ebraminio** [comment]
من مشکلی پیدا نکردم، احتمالاً کدتون رو هم باید ببینم، ممنون

**Comment by aysha319** [comment]
ممنون
شرمنده
دقیق تر چک کردم اشکال از یه سری تغییرات خودم بوده

**Comment by ebraminio** [comment]
عالی، یادتان باشد طبق مجوز این کد باید در پروژه‌ای هماهنگ با جی‌پی‌ال از
این آن استفاده کنید و چون کد من نیست نمی‌توانم مجوز استفاده‌ای دیگر را برای
شما ممکن کنم ممنون :)
