### ISSUE TITLE
تگ‌های اچ‌تی‌ام‌ال در رویدادهای ایمپورت شده از گوگل کلندر نسخه وب

### ISSUE THREAD

**Issue by saeedesmaili** [ebraminio/DroidPersianCalendar#291]
در رویدادهایی که در گوگل کلندر وب وارد شدن و داخل این اپ به صورت خودکار ایمپورت میشن،‌ تگ‌های اچ‌تی‌ام‌ال هم در متن میان:
https://calendar.google.com

Notice the "Test title 2" event:

![image](https://user-images.githubusercontent.com/13351748/43832157-bbe5bba2-9b1b-11e8-9b74-feb6ab5bf6ff.png)

![image](https://user-images.githubusercontent.com/13351748/43832259-1c9f30c2-9b1c-11e8-9fc0-98013e9dfe89.png)

- "Test Title 1" is created in Google Calendar android app.
- "Test Title 2" is created in Google Calendar web app (https://calendar.google.com).

**Comment by ebraminio** [comment]
چه خوب که مشکل را گزارش کردید و چه بد که زودتر متوجه آن نشده بودیم، ممنون :)
