### ISSUE TITLE
 همگام سازی با تقویم جیمیل

### ISSUE THREAD

**Issue by paymanzox** [ebraminio/DroidPersianCalendar#292]
سلام .اولا تبریک بگم بابت برنامه خیلی خوبه به نظرم.فقط اگر امکان سینم شدن با تقویم گوگل یا مایکروسافت اضافه بشه خیلی بهتر میشه

**Comment by ebraminio** [comment]
سلام! همین گونه هم هست و برنامه هیچ اطلاعاتی را در خود ذخیره نمی‌کند :)اگر در عمل چنین نبود، کافی است هنگام ذخیره‌سازی رویداد جدید گزینه همگام‌سازی را بررسی کنید که ببینید در کجا ذخیره می‌شود. اگر هم مشکل نمایش رویداد است کافی است از تنظیمات آن را فعال کنید. موفق باشید :)
