### ISSUE TITLE
نمایش انگلیسی نام اذان بعدی در ویجت

### ISSUE THREAD

**Issue by molaeiali** [ebraminio/DroidPersianCalendar#293]
نام اذان بعدی در ویجت به زبان انگلیسی نوشته میشه، مثلا
Dhuhr
به جای ظهر
ورژن ۵.۸‌.۸

**Comment by ebraminio** [comment]
درست می‌فرمایید مشکل از اندروید است که گاهی زبان تنظیم شده را برای برنامه عوض می‌کند.

در اینجا سعی کردم حداقل آن را به حالت قبلی برگردانم که امیدوارم در نسخهٔ بعد این مشکل کمتر دیده شود، ممنون

https://github.com/ebraminio/DroidPersianCalendar/commit/daf8dba994475bcee8686a7a4481d2ae52b4bad5#diff-4bcdc78626f206f8e14175629ca0ebd2R85
