### ISSUE TITLE
موقعیت جغرافیایی

### ISSUE THREAD

**Issue by fcbwin** [ebraminio/DroidPersianCalendar#297]
موقعیت جغرافیایی با وجود روشن بودن جی پی اس تعیین نمیشه. یا موقعیت یابی رو از طریق اینترنتی انجام بشه یا لیست همه شهرستان ها رو داشته باشین تا بصورت دستی انتخاب کنیم. فعلا فقط شهرهای بزرگ موجودن

**Comment by ebraminio** [comment]
نسخهٔ بعد احتمالاً بهتر می‌شه، ممنون :)
