### ISSUE TITLE
اضافه کردن قابلیت برنامه شیفت

### ISSUE THREAD

**Issue by saeednews** [ebraminio/DroidPersianCalendar#298]
سلام و خسته نباشید بابت برنامه مفید و کاربردی تقویم،در صورت امکان قابلیت نمایش شیفت کاری به برنامه افزوده بشه... برای مثال من بصورت ۵شیفت گردشی سرکار میرم میخوام بدونم ۱۷ام شیفت کاریم چی هست باید دستی محاسبه کنم که اگه قبول زحمت بفرمایید به برنامه همچین امکانی افزوده بشه

**Comment by saeednews** [comment]
تقویم بادصبا رو نگاه میکردم لیست کاملی از انواع شیفت‌هارو داره بخصوص شیفت کاری‌های مثل ما که کم اجرا میشه... یک روز صبح یک روز عصر یک روز شب یک روز تعطیل اول یک روز تعطیل دوم

**Comment by ebraminio** [comment]
سلام سعید جان، این امکان چه شکلی است، کمی درباره‌اش توضیح می‌دهید؟ آیا امکان قرار دادن رویداد تکرار شونده برای آن کافی نیست؟ ممنون :)

**Comment by ebraminio** [comment]
از ایمیل یکی از کاربران:

 خواهشمندم امکان افرودن نوبت کاری های مختلف مانند 4 روز کار 4 روز عصرکار 4 شبکار و 4 روز استراحت را به برنامه اضافه کنید

**Comment by ebraminio** [comment]
ایمیلی دیگر

من شیفت کاریم ۱ روز روزکار، ۱روز شبکار، ۱ روز استراحت. من یک تاریخی رو  به عنوان روزکار عادی مشخص کنم خود نرم افزار ما بقی روزارو شیفت بندی کنه و در تقویم نمایش بده

**Comment by ebraminio** [comment]
این قابلیت پیاده‌سازی شده فقط مانده جزئیات آن که تا نسخهٔ بعد نهایی می‌شود، ممنون :)
