### ISSUE TITLE
طولانی شدن تنظیمات

### ISSUE THREAD

**Issue by carp3** [ebraminio/DroidPersianCalendar#303]
<p dir='rtl' align='right'>
سلام،
</p>
<p dir='rtl' align='right'>
 با توجه به طولانی و زیاد شدن تنظیمات پیشنهاد میکنم قسمت تنظیمات دسته بندی بشه. هرچند یک دسته بندی در حال حاضر وجود داره اما دارای دکمه های جدا نیست.
 پیدا کردن یک تنظیم در صورتی که موقعیت حدودیش رو ندونید کار سختیه.
</p>
<p dir='rtl' align='right'>
پیشنهاد من اینه که بعد از فشردن دکمه تنظیمات. یک لیست از دسته بندی ها باز بشه و بعد از فشار دادن هر یک از اونها، تنظیمات مربوط به همون بخش باز بشه.
</p>

**Comment by ebraminio** [comment]
درست می‌فرمایید، باید چندصفحه‌ای بشود

**Comment by ebraminio** [comment]
چند صفحه‌ای نشد ولی گزینه‌های اضافی به «بیشتر» منتقل شد که در نسخهٔ بعد مشاهده می‌شود :)
