### ISSUE TITLE
2 Small Bugs

### ISSUE THREAD

**Issue by ilali** [ebraminio/DroidPersianCalendar#31]
1- در نسخه جدید (404) یک باگ کوچک وجود دارد که گاهی آخرین روز ماه را در خط پایین زیر نوشته ها نشان میدهد برای مثال روز 30 ماه آذر سال 1392 اینگونه است و زیر نوشته ها پنهان شده است. 
2- در پوسته روشن رنگ زمینه روز کنونی خیلی شبیه رنگ بقیه روزهاست که تشخیص آنرا مشکل میکند.

**Comment by ebraminio** [comment]
ممنون بابت باگ و شرمنده بابت تأخیر، با تغییرات ظاهری بزرگی که در راه است برطرف می‌شود
