### ISSUE TITLE
عدم به روز رسنی تقویم در نسخع ۴.۲.۲

### ISSUE THREAD

**Issue by eblueman** [ebraminio/DroidPersianCalendar#32]
علارغم عملکرد بسیار عالی در نسخه های قبلی با به روز رسانی سیستم به ۴.۲.۲ تاریخ به روز رسانی نمی گردد.

**Comment by ebraminio** [comment]
این مشکل بیشتر از نبود رم در گوشی و پر شدن آن توسط برنامه‌های دارای مشکل ناشی می‌شود، البته می‌شود کاری کرد که هر روز یک بار دوباره نوتیفیکیشن ران شود. 
@behdad222 @hamidsafdari

**Comment by behdad222** [comment]
@ebraminio ok

**Comment by ebraminio** [comment]
احتمالاً با تغییراتی که انجام داده شده در نسخهٔ جدید که البته هنوز منتشر نشده برطرف می‌شود، البته سعی می‌کنم از دوستانی که این مشکل را دارند بپرسم و البته حتی با بستن این فایل نیز موضوع را فراموش نمی‌کنم.
