### ISSUE TITLE
الگوریتم محاسبه تاریخ قمری

### ISSUE THREAD

**Issue by ghost1372** [ebraminio/DroidPersianCalendar#328]
سلام امکانش هست الگوریتم محاسبه دقیق تاریخ قمری رو کمی توضیح بدین یا همین کلاس هایی که برای این برنامه استفاده کردید رو برای سی شارپ قرار بدین؟

**Comment by ebraminio** [comment]
سلام، قمری دردسر واقعی است و هنوز نهایی نشده و الگوریتم‌های فعلی در 
https://github.com/ebraminio/DroidPersianCalendar/tree/master/PersianCalendar/src/main/java/calendar
DateConverter
IslamicDateConverter
UmmAlQuraConverter
که بنا به نیاز از یکی از آن‌ها استفاده می‌شود و تست‌هایی هم برای آن‌ها نوشته شده، و اگر به حالت پایداری رسید احتمالاً شاید آن را برای زبان‌های دیگر به مانند
https://gist.github.com/ebraminio/5292017
ایجاد کردم، ممنون :)

**Comment by ghost1372** [comment]
الگوریتم شما یکی از دقیق ترین الگوریتم های موجود رایگان بود که من تونستم پیدا کنم، مخزن شما رو به یکی از دوستان برنامه نویس معرفی کردم و ایشون هم لطف کردن و نسخه مشابه رو برای سی شارپ توسعه دادن، هم میتونید الگوریتم توسعه داده شده رو داخل مخزن خودم مشاهده کنید
https://github.com/ghost1372/MoalemYar
هم کتابخونه دوست عزیزمون که زحمت این کار رو کشیدن
https://github.com/VahidN/DNTPersianUtils.Core

**Comment by ebraminio** [comment]
خیلی جالب بود! خب کار من هم کمتر شد، ممنون :)
