### ISSUE TITLE
تنظیمی برای عدم نمایش نوار نوتیفیکیشن در نوار قفل 

### ISSUE THREAD

**Issue by kulakat** [ebraminio/DroidPersianCalendar#332]
با سلام خدمت تیم سازنده اپ 
persian calender
 درباره آیکون بالای صفحه که روز شمار است  
 میخواستم  یک درخواست کنم که وقتی صفحه گوشی 
 خاموشه ودکمه پاور میزنیم که تاریخو چک کنیم فقط همون آیکن کوچیک بالای صفحه باشه نه یک نوار سرتاسری وسط صفحه که عکس صفحرو ناقص کنه.
امید وارم خوب توضیح داده باشم با تشکر.

**Comment by ebraminio** [comment]
سلام! ممنون :) برنامهٔ دیگه‌ای سراغ دارید که اینگونه باشد؟

**Comment by ebraminio** [comment]
شدوساکس
https://github.com/shadowsocks/shadowsocks-android/blob/master/core/src/main/java/com/github/shadowsocks/bg/ServiceNotification.kt#L91

**Comment by ebraminio** [comment]
شدوساکس ظاهراً به کمک اولویت مین برای نوتیفیکیشن اینطور کار می‌کند که وقتی صفحه قفل است اولویت را به مین تغییر می‌دهد که نه نواری نشان داده شود و نه آیکونی و وقتی صفحه باز شد آن را لو کاهش افزایش می‌دهد، آنچیزی که الآن در تقویم داریم. ظاهراً چنین چیزی ممکن نیست مگر اینکه فکر دیگری به ذهنمون برسه

**Comment by ebraminio** [comment]
ظاهراً راهی نیست تا چیزی به ذهنمان بیاید ممنون :)

**Comment by kulakat** [comment]
ممنون از رسیدگی شما
من هنوز از Prsian Calendar استفاده میکنم.


On Sep 7, 2018 11:58 AM, "Ebrahim Byagowi" <notifications@github.com> wrote:

Closed #332 <https://github.com/ebraminio/DroidPersianCalendar/issues/332>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ebraminio/DroidPersianCalendar/issues/332#event-1832176158>,
or mute the thread

**Comment by ebraminio** [comment]
ممنونم :) شخصا گاهی کلا نوار آگاهی را قطع می‌کنم از ویجت استفاده می‌کنم یا از امکان جدید آیکون استاتوس اندرویدهای جدید آن‌ها را آزمایش کنید :)
