### ISSUE TITLE
[Enhancement] Add more location

### ISSUE THREAD

**Issue by pupyc** [ebraminio/DroidPersianCalendar#333]
Hi there,

Nice to see FOSS app, for this kind of purpose (Prayer times and Qibla compass etc...).
I have several request hope you have time to implement them.

1. Add more locations to fixed prayer times from https://github.com/KosratDAhmad/MyPrayersData.

> I used the location permissions. added the exact Latitude and Longitude and tried all different calculation methods but unfortunately none of them match the local prayer times.

2. Add an option to sync "Islamic Calendar" with Um-alQura calendar, or alternatively add "-2 -1 0 +1 +2" options , so it will be possible to manually change it.

> There is a 1 day difference between some countries in the "Islamic Calendar", so I think the best option would be to include and option to modify the date (like I mentioned above).  "[My Prayers](https://play.google.com/store/apps/details?id=com.kosratdahmad.myprayers)" and "[Taqwemee](https://play.google.com/store/apps/details?id=ws.xsoh.taqwemee)" implemented this nicely.![Image Taqwemee adjust Hijri Day feature](
https://lh3.googleusercontent.com/GltWf1Q2p5q8drIi5a44IVZ6mO1gqTfd4NDA64QoScC3qzvO7_DPG6CER5n-OzJ9qw=w1600-h785)

3. An option to view the full month's prayer times (priority low).

4. Add Iraq Events (I can help with this if you decide to add :).

5. Add Arabic language.

I don't use the applications mentioned above 1. does no work without google play services 2. has ads. :(

References
https://datehijri.com/

**Comment by pupyc** [comment]
Isn't there any API for Hijri Calendar in android, after google started supporting Hijri calendar in the `Google Calendar` app officially ?

**Comment by ebraminio** [comment]
Handling these on chat :)
