### ISSUE TITLE
زمان مانده به وقت شرعی

### ISSUE THREAD

**Issue by ali-star** [ebraminio/DroidPersianCalendar#34]
لطفا زمان مانده به وقت شرعی بعدی را به نرم افزار اضافه کنید. مثال:
2 ساعت و 30 دقیقه مانده به اذان صبح

**Comment by mahdavi75** [comment]
بنظر میرسد که با ویجت جدید، این خواسته تقریبا برآورده شده

**Comment by ebraminio** [comment]
درست است تقریباً برآورده شده، ممنون :)
