### ISSUE TITLE
تغییر نام ماها

### ISSUE THREAD

**Issue by alireza268** [ebraminio/DroidPersianCalendar#342]
با درود و عرض ادب
مدتی هست که نام ماه بجای مثلا خرداد یا شهریور ... اسد و سنبله یا اینجور میاد هرچه جستجو کردم نتونست تغییر بدم. لطفا راهنمائی بفرمائی. سپاس فراوان و با آرزوی پیروزی

**Comment by ebraminio** [comment]
سلام! در تنظیمات، در زبان، به جای دری، فارسی را انتخاب کنید و نتیجه حتماً بگویید ممنون :)
