### ISSUE TITLE
رفع مشکل

### ISSUE THREAD

**Issue by alireza268** [ebraminio/DroidPersianCalendar#345]
با درود و عرض ادب
بسیار سپاسگذارم حل شد یه پیشنهاد هم دارم اگه بتونین گزینه هوا شناسی رو هم بگنجونید عالی میشه و همینطور ساعت فورم آنالوگ اینطو دیگه نیازی به سایر برنامه ها نیست پیروز باسید

**Comment by ebraminio** [comment]
سلام علیرضای گرامی، هواشناسی نیازمند دسترسی اینترنت و خرید یا هماهنگی با مرجعی برای ارائهٔ چنین محتویاتی است و ساعت فورم آنالوگ دیگر در اندروید توصیه نمی‌شود که استفاده شود
https://developer.android.com/reference/android/widget/AnalogClock
به خاطر همین این دو را نمی‌توان انجام دهید و مشکل دیگری داشتیدمی‌توانید ایشوی دیگری باز کنید، ارادت، ممنون :)
