### ISSUE TITLE
گرافیک منوی اصلی برنامه

### ISSUE THREAD

**Issue by venusbahar** [ebraminio/DroidPersianCalendar#347]
طراحی و گرافیک منوی اصلی تقویم در به‌روز رسانی ۵.۹.۴ خیلی ساده‌ست و انگار یک چیزی کم داره! بهتره از المان‌های گرافیکی برای مجزاسازی بخش‌ها استفاده بشه.
اگر تقویم روز و مناسبت‌ها و اوقات شرعی مثل قبل به صورت زیر هم و باز شونده باشه بهتر خواهد بود.

**Comment by ali-hardan** [comment]
سلیقه‌ای هست.  اتفاقا طراحی جدید من رو شوکه کرد و بسیار پسندیدم. سادگی و تمیزی و جمع و جوری.

**Comment by ebraminio** [comment]
پس با اجازه این ایشو رو می‌بندم ولی قطعاً جای کار داره طبیعتاً، ممنون :)
