### ISSUE TITLE
نمایش تاریخ شمسی در تقویم آندروید

### ISSUE THREAD

**Issue by mashayekhi** [ebraminio/DroidPersianCalendar#35]
پیشنهاد می گردد به منظور نمایش تاریخ شمسی در ویجت اس پلنر آندروید بجای درج آن در دیسکریپشن در لوکیشن درج گردد؛

**Comment by behdad222** [comment]
@mashayekhi توضیح بیشتر لطفا

**Comment by ebraminio** [comment]
راستش از آنجایی که در حال حاضر گوشی‌های سامسونگ نداریم و نتیجهٔ جستجو نیز راهنمای زیادی برنگرداند بعید می‌دانم بتوانم مشکل را برطرف کنیم، شرمنده
