### ISSUE TITLE
یه ویجت ۴در۴ به برنامه اضافه کنید تا علاوه بر نشون دادن تاریخ و مناسبت ها ، اوقات شرعی رو هم نشون بده

### ISSUE THREAD

**Issue by ebraminio** [ebraminio/DroidPersianCalendar#350]
از ایمیل‌های دریافتی

**Comment by ebraminio** [comment]
البته دربارهٔ امکان‌پذیری و نیاز آن نیز باید تصمیم‌گیری کنیم

**Comment by runo280** [comment]
من خودم که خیلی دوست دارم، پول رکوئست بدم مرج می کنید؟

**Comment by ebraminio** [comment]
فونت نه خواهشا دردسر داره :/ اون وقت باید ریموت‌ویجت بیت‌مپ استفاده کرد چون مستقیم نمی‌شه فونت ست کرد و فونت فعلی خوبه وزیر شاید از اردو و کردی که ما پشتیبانی می‌کنیم کامل پشتیبانی نکنه یا تست نشده باشه برای اون زبون‌ها یا برای همه گوشی‌های قدیمی، همون فونت‌های گوگل رو استفاده کنیم فعلاً به نظرم یا نمی‌دونم بهش فکر کنیم، تغییری خواستید ایجاد کنید مشکلی چرا مرج نشه ولی ممکنه یه ذره بهش گیر بدم اگه بتونمم خودم برطرفش می‌کنم :) قضیهٔ دسترسی‌پذیری (رابط نابینایان) هم مهمه ولی چیز خاصی نیست فکر کنم بعد از تغییراتتونم بتونم ردیفش کنم، ممنون :)

**Comment by runo280** [comment]
این همه پیش رفتم، فقط نمیدونم وقته ادامه دادنشو پیدا می کنم یا نه، ریزه کاری هم کم نداره
بار اول یادم رفت همه فایلها رو کامیت کنم، نتونستم هم برش گردونم تا یجا کامیت کنم نهایتا شد دو تا کامیت 😶

[اولی
](https://github.com/runo280/DroidPersianCalendar/commit/d0f0e5b4b7c62ed2b04930a55e2b0fe89f3da6ad)
[دومی](https://github.com/runo280/DroidPersianCalendar/commit/d244e8405119116a7d01e420ef883433c9352cfa)

![screenshot_20181230-103940_nova_launcher](https://user-images.githubusercontent.com/13608702/50545218-e52e9480-0c21-11e9-8542-d79c0bb89e2e.png)

**Comment by ebraminio** [comment]
عااااالیه دسترسی‌پذیریش هم اوکیه چون از ویجت‌ها استاندارد استفاده شده، عااالیه

**Comment by ebraminio** [comment]
یه متنی نوشته بشه بگه مکان تنظیم نیست برای اوقات شرعی هم خوبه، بین‌المللی‌سازی‌ش یکم دردسره به خاطر همین استرینگ بذاریتش و تو یه کامیت جدا، اگه کلاً خواستید اگه نه هم پول رکوئست بزنید که سریعاً مرج کنم، ممنون :)

**Comment by ali-hardan** [comment]
‫سلام. این دقیقاً همون چیزی هست که دوست داشتم این نرم‌افزار داشته باشه! ظاهرش واقعاً عالی شده. آقای @runo280، بسیار تشکر.

‫منتظرم مرج و منتشر بشه.

آیا مناسبت‌ها رو هم نشون میده؟

**Comment by runo280** [comment]
> ‫سلام. این دقیقاً همون چیزی هست که دوست داشتم این نرم‌افزار داشته باشه! ظاهرش واقعاً عالی شده. آقای @runo280، بسیار تشکر.
> 
> ‫منتظرم مرج و منتشر بشه.
> 
> آیا مناسبت‌ها رو هم نشون میده؟

فعلا مناسبت ها رو نشون نمیده، البته سایزش ۴در۲ هست.

**Comment by ebraminio** [comment]
ویجت ۴در۲ الآن خیلی خوب شده ولی خب جای مناسبت‌ها رو نداره، به نظرم می‌شه این ایشو رو بست دیگه، ممنون گرامی :)
