### ISSUE TITLE
مشکل ناشناخته موندن ماژول اصلی برنامه

### ISSUE THREAD

**Issue by beigirad** [ebraminio/DroidPersianCalendar#358]
<div dir="rtl">
در اندروید استدیو ۳ و ۳.۲ مشکل بیلد نشدن و ناشناخته موندن ماژول PersianCalendar وجود داره که با اضافه کردنش هم مشکلات دیگه ای مانع از بیلد شدن و اجرای برنامه میشه.
</div>
![Shot](https://imgur.com/a/kLYGlt1)

**Comment by HrBDev** [comment]
در مراحل ایمپورت گردل رو انتخاب کنید
 
![image](https://user-images.githubusercontent.com/25826502/46314891-abc19b00-c5d8-11e8-8e79-9c0f737c3b65.png)

**Comment by ebraminio** [comment]
<div dir="rtl">
اندروید استودیو بعضی وقتا بازی درمیاره ولی باید کار کنه، پروژه را باز بسته کنید و گریدل رو پاک کنید که دوباره بگیره
</div>

**Comment by ebraminio** [comment]
فکر کنم کار دیگه‌ای نمی‌شه کرد اینجا، فعلاً می‌بندم این فایل رو
