### ISSUE TITLE
باگ احتمالی در ویجت نسخه 4.04

### ISSUE THREAD

**Issue by hamidrezabstn** [ebraminio/DroidPersianCalendar#36]
ویجت برنامه مثلا با ارتفاع 1 یعنی 1*2 یا1*3 و... 
باعث میشود تا نوشته های نمایش داده شده به خوبی دیده نشوند و نیمه ی پایین آن در کادر قرار نگیرد.
البته این مشکل در گوشی اچ تی سی دیزایر وی مشاهده شده است.

**Comment by behdad222** [comment]
@hamidrezabstn میشه اسکرین شات تهیه کنید؟

**Comment by ebraminio** [comment]
احتمالا مشکلی در صفحه گوشی خاصی است، با پوزش بابت بستن ایشو اگر دوباره آن را مشاهده کردید لطفاً در اینجا پیام بگذارید تا باز کردن مجدد ایشو مشکل را بررسی کنیم. ممنون از شما گرامی
