### ISSUE TITLE
Change default persian font

### ISSUE THREAD

**Issue by vahid-m** [ebraminio/DroidPersianCalendar#366]
Please use a different persian font instead of default android font. There are several open source persian fonts they are optimized for UI and readability.
For instance Vazir and Shabnam are very interesting fonts.

**Comment by rezazoom** [comment]
Wow, I've opened another issue a moment ago.
I need this feature too.

**Comment by ebraminio** [comment]
سلام! فونت اشاره شده از پشتو حمایت نمی‌کنه، در برنامه تلاش شده که انحصار به کشور و تقویم خاصی وجود نداشته و حتی زبان (تاجای ممکن یعنی) به خاطر همین نظرم بیشتر اینه چنین کاری رو نکنیم تا روزی که فونت بین‌المللی‌تری داشته باشیم، ممنون :)

**Comment by ebraminio** [comment]
پیشنهادهای دیگری هم داشتید حتماً بفرمایید

**Comment by ebraminio** [comment]
و فونت‌های دیگر
