### ISSUE TITLE
انتخاب مناسبت های مختلف بصورت پیش فرض

### ISSUE THREAD

**Issue by arash-brz** [ebraminio/DroidPersianCalendar#369]
سلام.ممنون از کد خوبتون.
من میخوام بعضی از گروه های مناسبت های موجود در تنظیمات هنگام نصب برنامه بصورت پیش فرض انتخاب شده 
باشند.
مثلا مناسبت های افغانستان و مناسبت های بین المللی بصورت پیش فرض هنگام نصب انتخاب شده باشن
چطوری باید این کار رو انجام بدم.
باتشکر

**Comment by ebraminio** [comment]
سلام! آرش جان امکانش نیست که از همین تقویم فارسی استفاده بشه؟ من همهٔ سعیم رو کردم که برنامه مختص یه کشور نباشه، حیفه اینطوری دودستگی به وجود بیاد، ممنون
