### ISSUE TITLE
مشکل تاریخ قمری

### ISSUE THREAD

**Issue by ali-star** [ebraminio/DroidPersianCalendar#37]
عید فطر در سال 1435 هجری قمری برابر 1 شوال میباشد ولی در نرم افزار 2 شوال است و آخرین روز ماه رمضان 30 میباشد نه 30 ام.

**Comment by ebraminio** [comment]
ممنون از شما گرامیان، احتمالا نیاز به افژودن گزینه تصحیح دستی قمری است که در #53 در نظر گرفته شده است
