### ISSUE TITLE
ویجت برنامه

### ISSUE THREAD

**Issue by Ebi-code** [ebraminio/DroidPersianCalendar#372]
ممنون از برنامه عالی که ارائه دادید. کلا بادصبا رو حذف کردم و برنامه خوب شما رو نصب کردم. از همه مهمتر قسمت رویدادهای باستانیه که خوشم اومده. 
فقط اگه امکانش هست روی ویجت برنامه بیشتر کار بشه. فونت و اندازه فونت قابل تفییر بشه. 
سپاس از زحماتتون
با تشکر

**Comment by ebraminio** [comment]
سلام! یه ویجت ۴در۲ اضافه شده، تغییر فونت که سخت هست ولی تغییر فونت  #351 مطرح شده پس این ایشو رو می‌بندم و البته ویجت‌ها واقعاً جای کار دارند... ممنون :)
