### ISSUE TITLE
فونت اسکرین سیور و نوتیفیکیشن

### ISSUE THREAD

**Issue by Masoud60** [ebraminio/DroidPersianCalendar#373]
سلام
سایز فونت اسکرین سیور و نوتیفیکیشن خیلی کوچیکه. در کل نرم‌افزار بین نرم‌افزار های هم نوع خودش خوبه.

**Comment by ebraminio** [comment]
سلام مسعود جان لطفاً تصویری از مشکلتان ارسال کنید، ممنون :)

**Comment by ebraminio** [comment]
تغییر فونت نوتیفیکیشن خیلی سخت هست و به قیمت شبیه سیستم نبودن نوتیفیکیشن تمام می‌شود که از انجامش معذورم :/ با این حال مشکل خاصی داشتید حتماً تصویر هم ارسال کنید، ممنون :)
