### ISSUE TITLE
قمری یک روز جلوست

### ISSUE THREAD

**Issue by Arya766** [ebraminio/DroidPersianCalendar#38]
با سلام و تشکر از تقویم اپن‌سورس، کم‌حجم و زیبا در عین حفظ سادگی، تقویم روزهای قمری را یک روز جلو نشان میدهد، و در حالی که تعطیلات به درستی در جای خود قرار گرفته‌اند، روز عاشورا (=۱۰ محرم) را، ۱۱ محرم نشان میدهد.
خیلی عالی بود اگر:
۱. تنظیمات قمری میداشت و اجازه میداد کاربر یکی دو روز جابه‌جا کند.
۲. اوقات شرعی را در ویجت نشان میداد
۳. اجازه میداد کاربر شفافیت ویجت را تنظیم کند.
مجددا از زحمات شما ممنون و متشکرم

**Comment by ebraminio** [comment]
ممنون از شما گرامی بابت باخورد خوبیتان، این ایشو بهرترتبب به سه قسمت تبدیل شد، #53 #41 #71 ممنون :)
