### ISSUE TITLE
اشتباه نشان دادن تاریخ

### ISSUE THREAD

**Issue by D32Secret** [ebraminio/DroidPersianCalendar#381]
امروز 30 دی 97 رو 1 بهمن نشون میده
اپدیت هم کردم

**Comment by ebraminio** [comment]
سلام! امروز ۱بهمن هست تاجایی که می‌دانم، گوگل نیز چنین می‌گوید، شاید ساعت دستگاه‌تان تنظیم نیست یا موقعیتش روی ایران نیست؟

**Comment by ebraminio** [comment]
ممنون :)
