### ISSUE TITLE
جا به جا بودن قبل از ظهر و بعد از ظهر

### ISSUE THREAD

**Issue by fakhamatia** [ebraminio/DroidPersianCalendar#389]
سلام
توی قسمت اوقات شرعی ق.ظ. و ب.ظ. رو برعکس نشون میده

**Comment by ebraminio** [comment]
درست می‌فرمایید، در نسخهٔ بعد اصلاح می‌شود

**Comment by ebraminio** [comment]
و ممنون بابت گزارش‌ :)
