### ISSUE TITLE
نمایش تاریخ در نوتیفیکیشن

### ISSUE THREAD

**Issue by fcbwin** [ebraminio/DroidPersianCalendar#393]
سلام
لطفا در نوار نوتیفیکیشین بجای لوگوی برنامه عدد همون روز نمایش داده شود
قبلا این کار رو میکردید خیلی خوب بود ولی بعد حذفش کردید
عکسشو ضمیمه میکنم
http://uupload.ir/files/26lr_img_20190209_184902.jpg
همچنین گوشی بنده شیائومی هستش و در تنظیمات برنامه گزینه محافظ قفل صفحه رو فعال کردم ولی وقتی صفحه گوشیم خاموشه تاریخ نمایش داده نمیشه
لطفا بررسی کنید
ممنون بابت برنامه خوبتون

**Comment by ebraminio** [comment]
سلام! احتمال خیلی خیلی زیادی از خود سیستم هست ما واقعاً کاری نکردیم که اینطور بشه یا بتونیم جلوشو بگیریم چون در باقی گوشی‌ها اینطور نیست :/

**Comment by ebraminio** [comment]
تاجایی که می‌دانم کاری از دستمان برنمی‌آید، شرمنده
