### ISSUE TITLE
اشکال در عقب ماندن ساعت پرشین کلندر

### ISSUE THREAD

**Issue by mohamadromak** [ebraminio/DroidPersianCalendar#40]
سلام ممنون از اپ بسیار مفیدتون خدمت شما عرض داشتم که ساعت شما که با تاریخ شمسی و میلادی روی صفحه نمایان میشه از ساعت گوشی عقب میمونه مثلا طی 3 روز 12 دقیقه اختلاف ایجاد شده مثلا ساعت گوشی الان 19:22 رو نشون میده و ساعت پرشین کلندر 19:10 دقیقه رو نشون میده ینی روزی 4 دقیقه جا میمونه بازم ممنون از اپ موثر و خوبتون

**Comment by behdad222** [comment]
@mohamadromak 
نتیفیکیشن یا ویجت؟
بعد کار خاضی میکنید که هماهنگ میشه؟
مثلا بعد از ۳ روز میشه کاری کرد که تنظیم بشه؟

**Comment by ebraminio** [comment]
ادغام با #32 ممنون از شما گرامی
