### ISSUE TITLE
برنامه تقویم فارسی

### ISSUE THREAD

**Issue by alalisani** [ebraminio/DroidPersianCalendar#401]
با سلام
میخواستم گزارش کنم که مناسبت ها توی تقویم نشون داده نمیشه

نسخه نرم افزار ۶.۰.۱
نسخه اندروید ۷.۱

**Comment by ebraminio** [comment]
مناسبت‌ها را از تنظیمات فعال کرده‌اید؟ ممنونم

**Comment by alalisani** [comment]
ممنون، با فعال کردن تنظیمات مشکل حل شد

**Comment by ebraminio** [comment]
ممنونم
