### ISSUE TITLE
افزودن فونت

### ISSUE THREAD

**Issue by alireza-naghizadeh** [ebraminio/DroidPersianCalendar#404]
سلام و تشکر بابت اپ بسیار کاربردی و خوبتون
خواهشمندم درصورت امکان از فونت بهتری استفاده بشه، در تمامی بخشها بویژه ویجت ها
فونت ایران-سنس و ایران-یکان از مناسبترین فونتها هستند
متشکرم

**Comment by ebraminio** [comment]
سلام علیرضا جان، ممنون از شما، متأسفانه نمی‌توانیم از این فونت‌ها استفاده کنیم به این دلیل که با مجوز آزاد منتشر نشده‌اند و هدف این برنامه این بوده است که تاجای ممکن از چیزهایی که با مجوز آزاد منتشر شده‌اند استفاده کنیم. البته فونتی که در برنامه قابل استفاده باشد شرایط دیگری نیز باید داشته باشد از جمله حمایت از نویسه‌های کردی و پشتو، سخت پیدا می‌شوند پروژه‌های بومی که حساسیت‌های اینگونه داشته باشند ولی این پروژه در کشورهای همسایه نیز استفاده می‌شود به همین دلیل نیاز است اینگونه باشد. ممنونم
