### ISSUE TITLE
نبود پکیج databinding

### ISSUE THREAD

**Issue by CoderoidAcademy** [ebraminio/DroidPersianCalendar#406]
سلام. خسته نباشی
جناب پکیج
com.byagowi.persiancalendar.databinding
کلا نیستش
کجاس؟!

**Comment by CoderoidAcademy** [comment]
توی ورژن 
6.0.1
منظورم هست

**Comment by ebraminio** [comment]
درود گرامی، به صورت خودکار درست می‌شود، احتمالاً استودیوتان تنظیم نیست، موفق باشید :)
