### ISSUE TITLE
پیچیدگی و عدم امکان ویرایش تقویم و سفارشی سازی

### ISSUE THREAD

**Issue by nortonkh71** [ebraminio/DroidPersianCalendar#412]
باعرض سلام و خسته نباشید خدمت آقای بیاگوی
میخواستم بهتون اطلاع بدم که متاسفانه در نسخه جدید امکان ویرایش و سفارشی سازی تقویم وجود نداره و کدنویسی بسیار پیچیده شده است.
متاسفانه ما نتونستیم هسته تقویممونو به آخرین نسخه ارتقا دهیم و روی نسخه 5.8.8 مانده ایم.

نمی دانم امکان سفارشی سازی و ایجاد تغییرات در آیتم ها وجود دارد یا خیر ولی خواهشمندم اگر امکان دارد آموزشی درین باب ارائه دهید و یا نسخه ای از تقویم بر اساس معماری جاوا مانند قبل ارائه دهید.

**Comment by ebraminio** [comment]
سلام، متأسفانه تغییرات به همهٔ جزئیات بنا به نیاز همیشگی هستند، ای کاش طبق مجوز برنامه، جی‌پی‌ال، نسخهٔ خودتان را نیز متن‌باز منتشر می‌کردید، ممنونم و موافق باشید
