### ISSUE TITLE
اشکال در پخش اذان

### ISSUE THREAD

**Issue by martyr72** [ebraminio/DroidPersianCalendar#419]
به نام خدا و سلام. در نوکیا 6.1 با اندروید 9 وقتی که صدای اذان را تنظیم میکنم، به محض رسیدن وقت اذان میزان ولوم صدای اعلان برابر با صفر میشود و اذان قابل شنیدن نیست. سپاس از شما و برنامه بسیار عالی تان
پیروز باشید

===Device Information===
Manufacturer: HMD Global
Model: Nokia 6.1
Android Version: 9
App Version Code: ۶.۰.۱

**Comment by ebraminio** [comment]
سلام! تاجایی که می‌دانم از ولوم هشدارها گوشی هم تبعیت می‌کند که احتمالاً همان خاموش است

**Comment by martyr72** [comment]
در کلیه حالات ولوم هشدار صحیح عمل می کند و فقط در هنگام اعلام اذان به لحظه قطع می شود
چندین بار آنرا با برنامه های مختلف خصوصا زنگ ساعت امتحان کردم. هیچ مشکلی وجود ندارد ولی به محض شروع وقت اذان، برابر با صفر می شود

**Comment by ebraminio** [comment]
@MEHDIMYADI ایده‌ای دارید گرامی؟

**Comment by MEHDIMYADI** [comment]
سلام بر @martyr72  و @ebraminio 
سال نوتون مبارک
ابراهیم جان تو اذان قسمت AudioManager.STREAM_ALARM رو به AudioManager.STREAM_SYSTEM چجنچ کن یه نسخه براشون ارسال کن لطفا ببین مشکلشون پابرجاست آیا والا قدیما رو این قسمت خیلی کار کردم و بخاطر این گذاشتم رو الارم که چون کسی اون رو سایلنت نمیکنه احتمالا ایشون سایلنت کردن و فقط ویبره فعاله

**Comment by ebraminio** [comment]
@martyr72 اوه چرا

حمیدرضا ظاهراً ایده‌ای در این رابطه داشت

**Comment by martyr72** [comment]
سلام به @MEHDIMYADI , @ebraminio 
سال نو بر شما هم مبارک باشه
آقا مهدی گوشی در حالت سایلنت نیست. چندبار تنظیم ساعت رو در حالت دستی قراردادم و ساعت را نزدیک ساعت اذان تنظیم کردم. تنظیمات بلندی صدا را برای تمام قسمتها شامل: زنگ، رسانه، آلارم و غیره را زیاد کردم. ولی به محض رسیدن ساعت به وقت اذان همزمان با نمایش پخش اذان توسط برنامه تقویم فارسی، ولوم آلارم خودکار بر روی صفر می رود و صدایی پخش نمی شود.

**Comment by MEHDIMYADI** [comment]
ممنون ظاهرا باید بررسی شه
نسخه‌های متفاوت اندروید در کنار سفارشی سازی برندها، توسعه‌ دهنده ها رو بد کلافه کرده

**Comment by ebraminio** [comment]
در حال بررسی هستیم

**Comment by ebraminio** [comment]
https://github.com/ebraminio/DroidPersianCalendar/pull/422/commits/207a69856744f5ca98692ba2dd50653e3fbacf2d
@HrBDev با این برطرف شد؟

**Comment by HrBDev** [comment]
نه این باعث میشه تغییر صدا هنگام پخش اذان روی آلارم یا همون اذان اعمال بشه جای اینکه صدای اصلی رو عوض کنه

**Comment by MEHDIMYADI** [comment]
> 
> 
> نه این باعث میشه تغییر صدا هنگام پخش اذان روی آلارم یا همون اذان اعمال بشه جای اینکه صدای اصلی رو عوض کنه

سلام
بنظر من راه حل این مشکل همینی بود که ابراهیم جان انجام داد چون هر برنامه ای فعلا به هر نحوی چیزی برای ریمایند داره از آلارم استفاده میکنه فعلا البته تا ببینیم نسخه های آینده اندروید چه اتفاقی می افته

**Comment by MEHDIMYADI** [comment]
@ebraminio پیشنهادی دارم از دستور کی‌مپ استفاده میشه کرد و با کم و زیاد مقدار ولوم تو تنظیمات خود تقویم فارسی رو تغییر بده

**Comment by martyr72** [comment]
سلام به @MEHDIMYADI , @ebraminio
از زحمات شما عزیزان سپاسگزارم
با به روز رسانی جدید برنامه تقویم فارسی، مشکل حل شد
موفق و پیروز باشید

**Comment by ebraminio** [comment]
@martyr72 با تشکر از گزارشتان شما مشکل احتمالاً توسط حمیدرضا حل شد و در نسخهٔ بعد قرار خواهد گرفت :)
