### ISSUE TITLE
More material design...

### ISSUE THREAD

**Issue by mahdavi75** [ebraminio/DroidPersianCalendar#42]
سه ویژگی که بنظرم اومد بهتره که این نرم افزار داشته باشه.

۱. تاریخ میلادی بهتره که بصورت انگلیسی هم نشون داده بشه، یعنی: May/مه

۲. آیکن نرم‌افزار شکل متریال دیزاینی‌تر به خودش بگیره تا با طراحی جدید سیستم عامل اندروید هماهنگی بیشتری داشته باشه.

۳. با توجه به اینکه با لمس‌کردن ویجت نرم‌افزار میشه مستقیما به تنظیمات اون دسترسی داشت، پیشنهاد میکنم گزینه‌ای برای شو/هاید کردن آیکن نرم‌فزار از لیست اپلیکیشن‌ها درنظر گرفته بشه. به دلیل اینکه لانچر دیفالت گوشی‌های نکسوس یعنی "گوگل ناو لانچر"، مثل گوشی‌های سامسونگ قابلیت شو/هاید ندارند.

**Comment by ebraminio** [comment]
دومی در حال انجام است، سومی بعید است ممکن باشد، برای اولی ایشوی جداگانه ایجاد کردم. ممنون از شما گرامی :)
