### ISSUE TITLE
سوال در مورد مجوز تقویم

### ISSUE THREAD

**Issue by nortonkh71** [ebraminio/DroidPersianCalendar#420]
سلام آقای بیاگوی
ما در سورس جاوای تقویم شما دستی نبرده ایم و فقط تغییرات ظاهری در لایوت ها و رنگ ها و استایل ایجاد کرده ایم. و در توضیحات درون برنامه هم به نام شما و مخزن تقویم شما اشاره کرده ایم

آیا باز هم لازم سورس را منتشر کنیم؟

**Comment by ebraminio** [comment]
سلام گرامی بله احتیاطاً قرار دهید چون برنامه فقط شامل کدهای جی‌پی‌ال این پروژه و از کدهای جی‌پی‌ال پروژه‌های دیگر هم استفاده شده که مجوز آن را هم ندارم و از اس‌دی‌کی‌های تبلیغ هم استفاده نکنید زیرا متن‌باز نیستند و ترجیحاً جداگانه هم منتشر نکنید که کاربران گمراه نشوند و قابلیتی نیاز دیدید می‌توانید به همین پروژه اضافه کنید مانند سایر عزیزانی که اسمشان در صفحهٔ برنامه وجود دارد که این برنامه را تهیه کرده‌اند، ممنون و موفق باشید
