### ISSUE TITLE
خطا در سینک سورس

### ISSUE THREAD

**Issue by alirezaivaz** [ebraminio/DroidPersianCalendar#441]
سلام. من توی اندروید استودیو ۳٫۴ ورژن ۵٫۱ تا آخر سورس رو ایمپورت کردم، همشون موقع سینک این ارور رو می‌دن
`ERROR: CreateProcess error=2, The system cannot find the file specified Open File`
تا ورژن ۵٫۴ میشه یه کاریش کرد ولی بعد از اون دیگه هیچ جوره سینک نمی‌شه

**Comment by ebraminio** [comment]
سلام! احتمالاً در ویندوز کمی به خاطر دستورهای گیت بازی می‌دهد ولی در لینوکس و مک باید بدون مشکل کار کند

**Comment by alirezaivaz** [comment]
خب حلا من چی‌کار می‌تونم بکنم؟
ویندوزم ۱۰، نسخه ۶۴بیت

**Comment by ebraminio** [comment]
نمی‌دونم من همجین مشکلی تو ویندوز هم نداشتم البته، اون قسمت دستورای گیت رو غیر فعال کنید ببینید درست می‌شه آیا، ممنونم

**Comment by alirezaivaz** [comment]
> نمی‌دونم من همجین مشکلی تو ویندوز هم نداشتم البته، اون قسمت دستورای گیت رو غیر فعال کنید ببینید درست می‌شه آیا، ممنونم

دستورات گیت کجاست؟

**Comment by ebraminio** [comment]
https://github.com/ebraminio/DroidPersianCalendar/blob/master/PersianCalendar/build.gradle.kts#L43
این‌ها

**Comment by alirezaivaz** [comment]
اتفاقی سینک شد.
حالا generate signed apk رو زدم، نزدیک ۱۵ دقیقه هست که روی این گیر کرده:
`:PersianCalendar:lintVitalRelease`

**Comment by alirezaivaz** [comment]
![Screenshot (112)](https://user-images.githubusercontent.com/43664225/58323990-d21f9980-7e3a-11e9-9764-d956ba4f8cfc.png)
generate signed apk رو زدم، اینم نتیجه‌اش! بنظرتون عادیه!
پروژه رو دیلیت کردم و دوباره ایمپورت کردم که اینجوری شد، هم سینک شد هم ژنریت شد!
فقط فایل خروجی اسمش غیرعادی بود:
`PersianCalendar-release-6.1.0-null-null-null.apk`
این سه تا نال توی قسمت درباره اتوماتیک اضافه شدن:
![Screenshot_2019-05-24-22-32-04](https://user-images.githubusercontent.com/43664225/58348123-fa2bee80-7e74-11e9-9c6e-694c6b4c9863.png)
کلا عجیب و غریبه این اپ!!!

**Comment by alirezaivaz** [comment]
> generate signed apk رو زدم، اینم نتیجه‌اش! بنظرتون عادیه!
> پروژه رو دیلیت کردم و دوباره ایمپورت کردم که اینجوری شد، هم سینک شد هم ژنریت شد!
> فقط فایل خروجی اسمش غیرعادی بود:
> `PersianCalendar-release-6.1.0-null-null-null.apk`
> این سه تا نال توی قسمت درباره اتوماتیک اضافه شدن:
> کلا عجیب و غریبه این اپ!!!
البته ورژن رو چندبار عوض کردم آخرش هم شد همین که می‌بینید

**Comment by ebraminio** [comment]
می‌دونید مشکل اصلی اینه که گیت رو در کامند لاینتون ندارید

**Comment by ebraminio** [comment]
که خب برای دیباگ اینا استفاده می‌کنیم از خود دستور گیت و حالا که ندارید این مشکل‌ها پیش میاد

**Comment by alirezaivaz** [comment]
چجوری گیت رو داشته باشم؟

**Comment by ebraminio** [comment]
دستور گیت رو که در سی‌ام‌دی می‌زنید چه اتفاقی می‌افتد؟ اگر بدون مشکل کار می‌کند نمی‌دانم چرا پروژه آن را پیدا نمی‌کند اگر هم کار نمی‌کنید آن را نصب کنید

**Comment by noushinsoft** [comment]
`Warning:<i><b>project ':PersianCalendar': Unable to build Kotlin project configuration</b>
Details: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':PersianCalendar:debugImplementationDependenciesMetadata'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find vectordrawable.aar (androidx.vectordrawable:vectordrawable:1.0.1).
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable/1.0.1/vectordrawable-1.0.1.aar</i>
`

**Comment by noushinsoft** [comment]
با سلام
من هم مشکل این آقا رو داشتم منتها گیتها رو حذف کردم و اون اررور رفع شد 
یه اررور دیگه هست ممنون میشم دلیلشو بفرمایید.

Could not find vectordrawable.aar (androidx.vectordrawable:vectordrawable:1.0.1).
Searched in the following locations:
    https://dl.google.com/dl/android/maven2/androidx/vectordrawable/vectordrawable/1.0.1/vectordrawable-1.0.1.aar

**Comment by ebraminio** [comment]
سلام، فورک‌های غیراوپن‌سورس از آنجایی که با مجوز کدهای استفاده شده در برنامه هماهنگ نیستند مورد حمایت ما نیستند، لطفاً اوپن‌سورس کردن آن‌ها و بازگرداندن تغییراتتان را در برنامه مورد توجه قرار دهید، ممنون

**Comment by ebraminio** [comment]
البته منظور هیچ کدام از عزیزانی که اینجا پیام قرار داده بودند نیست، اگر به سی‌آی برنامه توجه کنید می‌بینید که بدون مشکل برنامه را کامپایل می‌کند و مشکلات دیگر مربوط به رایانهٔ شخصی‌تان است که البته گاهی من هم دارم
