### ISSUE TITLE
تغییر مختصات و بالارفتن دقت اذان

### ISSUE THREAD

**Issue by alirezaivaz** [ebraminio/DroidPersianCalendar#442]
سلام. فایل cities.json رو ویرایش کردم. اطلاعات مختصات رو از ویکی‌پدیا گرفتم، بیشتر مختصات من‌جمله مشهد اشتباه بودن و الان دقت اذان حتی به کمتر از ۱ دقیقه نسبت به واقعیت رسیده. امیدوارم که مفید باشه:

[cities.txt](https://github.com/ebraminio/DroidPersianCalendar/files/3219197/cities.txt)
(برای آپلود، فرمت رو تغییر دادم)

**Comment by ebraminio** [comment]
عااالی من الآن دسترسی برای ادغام و بررسی ندارم در این فرصت علاقه دارید تغییراتتان را به صورت پول رکوئست کنید؟ به نظر این گیت دسکتاپ را نصب کنید خیلی کارتان را ساده می‌کند برای یادگیری گیت
https://desktop.github.com/

**Comment by alirezaivaz** [comment]
حتما امتحان می‌کنم.

**Comment by alirezaivaz** [comment]
راستی من برنامه رو که خروجی کردم، روی چندتا شهر، با یک دقیقه شاید کم تر فرق داشت با واقعیت.

**Comment by alirezaivaz** [comment]
من چطور میتونم توی گیت‌هاب دسکتاپ پول رکوئست بدم؟ اول فایل رو جایگزین کردم بعد کامیت رو زدم، حلا باید چی‌کار کنم؟

**Comment by ebraminio** [comment]
اوه عااالی، اول باید تغییرو در فورک خودتون اعمال کنید بعد اپلودش کنید بع
فورک خودتون از ظاهر گیت‌هاب دکمه create pull requestخودتون رو بزنید، فکر
کنم گیت‌هاب دسکتاپ یه کارایی کرده برای ساده کردن اینکار
