### ISSUE TITLE
قسمت اطلاعات دستگاه فارسی شد

### ISSUE THREAD

**Issue by alirezaivaz** [ebraminio/DroidPersianCalendar#443]
فایل اطلاعات دیوایس رو براتون فارسی کردم:
E:\NougatCalendar\app\src\main\java\com\byagowi\persiancalendar\ui\about\DeviceInformationFragment
[DeviceInformationFragment.txt](https://github.com/ebraminio/DroidPersianCalendar/files/3219199/DeviceInformationFragment.txt)

**Comment by ebraminio** [comment]
سلام گرامی ترجمه در این برنامه دردسر بیشتری دارد و باید ترجمه شود و الآن ۷ ۸ زبان داریم به خاطر همین ترجیح می‌دهم حتی کاری که نیاز به ترجمه داشته باشد اصلاً انجام ندهم و الآن ترجمه‌های جدید این بخش باید به همان شیوه ترجمه شوند و دردسری خواهد بود :/ شرمنده‌ام
