### ISSUE TITLE
روزهای تعطیل قمری عوض شده ادیت بفرمایید 

### ISSUE THREAD

**Issue by siavashkhoshahval** [ebraminio/DroidPersianCalendar#444]
روزهای قمری یک روز عقب افتاده لطفا ادیت کنیین

**Comment by ebraminio** [comment]
درست می‌فرمایید این ماه تغییر کرده که می‌شود با تنظیم تقویم قمری در قسمت پیشرفته بخش اول تنظیمات اصلاحش کرد ولی انتهای ماه باید آن را به صفر برگرداند مگر اینکه یک آپدیت بدهم :/ ممنون

**Comment by siavashkhoshahval** [comment]
به نظرمن اگه آپدیت بدید بهتره چون تنظیماتی ک گفتین سخته و هرکسی نمیتونه
درستش کنه

**Comment by ebraminio** [comment]
سلام درست می‌فرمایید برای امسال که نرسیدیم و تمام شد ایشالا سال بعد بیشتر مراقب خواهیم بود ممنونم

**Comment by siavashkhoshahval** [comment]
خیلی ممنون از پیگیری خوبتون
