### ISSUE TITLE
حذف یا افزودن زبان

### ISSUE THREAD

**Issue by alirezaivaz** [ebraminio/DroidPersianCalendar#445]
من توی سورسی که واسه خودم ادیت کردم چجوری می‌تونم زبان‌ها رو حذف یا اضافه کنم؟ ممنون می‌شم اگه بگید (چون من کوتلین بلد نیستم و ممکنه اشتباهی کنم)

**Comment by ebraminio** [comment]
دردسرش زیاد هست، برای چه منظوری می‌خواید؟

**Comment by alirezaivaz** [comment]
می‌خوام چندتا زبان ر واسه خودم حذف کنم

**Comment by ebraminio** [comment]
خب سخت است و ما هم پشتیبانی رقیب نمی‌دهیم، منتظر تغییرات خوبتان در همین سورس هستیم :) ممنون
