### ISSUE TITLE
درخواست

### ISSUE THREAD

**Issue by mojtaba7b** [ebraminio/DroidPersianCalendar#446]
با عرض سلام و خسته نباشید
اقای بیاگوی درخواست دارم لطفا در صورت امکان نسخه اخر تقویم را در گیت هاب به صورت جاوا قرار دهید .متاسفانه هنوز آشنایی چندانی با کاتلین ندارم
ممنون 
با تشکر

**Comment by ebraminio** [comment]
سلام مجتبی جان از نظر فنی ممکن نیست

**Comment by mojtaba7b** [comment]
سلام اقای بیاگویی خسته نباشید
 لطفا مشکل بلندی صدا اذانی که توسط کاربر انتخاب شده را برطرف نمائید
و تقویم تا باز نکنیم تاریخ درست را نشان نمی دهد و عقب میوفته 
ممنون
