### ISSUE TITLE
مشکل در تغییر پکیج برنامه

### ISSUE THREAD

**Issue by CoderoidAcademy** [ebraminio/DroidPersianCalendar#447]
سلام، وقتت بخیر مهندس
وقتی میخوام تغییر پکیج بدم مثلا پکیج
رو تغییر بدم، کلاس های پکیج biagowi 
دیگه ساخته نمیشن. چرا؟ databinding

**Comment by CoderoidAcademy** [comment]
واسه چیه؟ databinding  اصلا این

**Comment by ebraminio** [comment]
سلام مربوط به ویوها هست، ولی منتظر تغییراتتان در سورس همین برنامه هستیم نیازی به پروژه جداگانه نیست :) ممنون
