### ISSUE TITLE
مشکل در تقویم هجری

### ISSUE THREAD

**Issue by CoderoidAcademy** [ebraminio/DroidPersianCalendar#448]
سلام
مهندس امروز ۲۹ رمضانه ولی تقویم زده ۳۰ رمضان. تاریخ شمسیش درسته
( ۱۴ خرداد )

**Comment by ebraminio** [comment]
سلام برای امسال که تمام شد ایشالا سال بعد بیشتر مراقب خواهیم بود ممنون :)
