### ISSUE TITLE
در خواست آموزش بیشتر برای استفاده از این پروژه

### ISSUE THREAD

**Issue by omidjoon** [ebraminio/DroidPersianCalendar#45]
با سلام 
من نیاز دارم یک همچین تقویمی رو در پروژه ام استفاده کنم اما چون با اندروید استادیوکار نمیکنم مشکل دارم 
اگر راهنمایی کنید ک چطور میشه ازین فایل در ایکلیپس استفاده کرد ممنون میشوم 
من به استایل calandarview نیاز دارم

**Comment by ebraminio** [comment]
<div dir="rtl">سلام. متأسفانه اطلاعی ندارم</div>
