### ISSUE TITLE
اوقات شرعی

### ISSUE THREAD

**Issue by ahonarvar** [ebraminio/DroidPersianCalendar#451]
سلام و وقت بخیر
قسمت اوقات شرعی را مثل سابق پیدا نمیکنم! خواهشی داشتم مبنی براینکه اوقات شرعی را در تقویم اضافه کنید
 سپاسگزار

**Comment by ebraminio** [comment]
سلام گرامی جهت دیدن اوقات شرعی کافی‌ست مکان را در تنظیمات مشخص کنید، ممنونم
