### ISSUE TITLE
تخلف

### ISSUE THREAD

**Issue by alirezaivaz** [ebraminio/DroidPersianCalendar#459]
سلام. من امروز با یک سایت مواجه شدم که سورس تقویم شما رو می‌فروشه!! آیا برخوردی با متخلف می‌کنید؟ اینم لینکش:
[شاپ‌دروید](https://shopdroid.ir/product/persian-date/)

**Comment by ebraminio** [comment]
سلام گرامی طبق مجوز جی‌پی‌ال که استفاده از آن به دلیل کدهایی بود که اسفاده کردیم، فروش مشکلی ندارد (هر چند شخصاً چنین استفاده‌ای را از سورس برنامه دوست ندارم) و تغییر و انتشار و منتشر نکردن سورس مشکل دارد

**Comment by ebraminio** [comment]
ممنونم
