### ISSUE TITLE
ساعت و یجت ها فارسی نیستند

### ISSUE THREAD

**Issue by clickmeplz** [ebraminio/DroidPersianCalendar#460]
از نگارش ۶ به بعد ساعت در ویجتها فارسی نیستند.
دستگاه : Mi 4
اندروید ۶

**Comment by ebraminio** [comment]
سلام گرامی بله چاره‌ای نداریم برای این مورد ارقام آن با زبان سیستم تنظیم است، شرمنده :/

**Comment by clickmeplz** [comment]
سلام...خب با زبان سیستم تنظیم نکنید. من بخاطر این مشکل برگشتم نگارش ۴
