### ISSUE TITLE
ژوئن - ژوئیه و اوت

### ISSUE THREAD

**Issue by eabdeyazdan** [ebraminio/DroidPersianCalendar#47]
سلام.
نام سه تا از ماه های میلادی را به اشتباه نوشته اید.
ژوئن - ژوئیه و اوت. 
اگه می‌خواهید نام انگلیسی ماه های میلادی را بجای نامهای فرانسوی شان استفاده کنید
باید همه آنها را به انگلیسی بنوسید همانند افغانی ها.
جانیوری - فبروئری - مارچ - اپریل - می - جون - جولای - آگست - سپتمبر - اکتبر - نوومبر و دیسمبر.

**Comment by ebraminio** [comment]
<div dir="rtl">ممنون، اصلاح شد</div>
