### ISSUE TITLE
مشکل در استفاده از تقویم بصورت ماژول

### ISSUE THREAD

**Issue by arash-brz** [ebraminio/DroidPersianCalendar#477]
سلام.ممنون از زحمت شما.من میخوام از این تقویم به عنوان قسمتی از یک پروژ] دیگه استفاده کنم.یعنی یکی از امکانات برنامه تقویم باشه.واسه همین تو برنامه تقویم رو به عنوان ماژول اضافه کردم.و علاوه بر این تقویم برنامه یک ماژول دیگه هم داره.وقتی میخوام در قسمت ماژول ها تقویم رو به عنوان دیپندنسی به ماژول دیگه برنامه اضافه کنم ،ماژول تقویم به عنوان یک ماژول در لیست افزودن دیپندنسی نمیاد.
تو تصاویر کاملا مشخصه

![explorer](https://user-images.githubusercontent.com/10999585/64819052-a0396b00-d5c2-11e9-81b4-b139429968da.png)

![modules](https://user-images.githubusercontent.com/10999585/64819037-97e13000-d5c2-11e9-86ae-4935dff8a639.png)

**Comment by ebraminio** [comment]
سلام آرش جان استفاده از تقویم به عنوان ماژول حمایت شده نیست و غیر از آن نرم‌افزاری که از کدهای جی‌پی‌ال استفاده کند باید قوانین جی‌پی‌ال را رعایت کند که استفاده از کتابخانه‌های جی‌پی‌ال دیگر ما را مجبور به آن کرده است، با عرض شرمندگی

**Comment by ebraminio** [comment]
بله شرایط جی‌پی‌الی که در اینجا خلاصه شده است
https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)

**Comment by arash-brz** [comment]
سلام مجدد.
توی استک اور فلو راه کار دادن که از پروژه های گیت هاب میتونم بصورت جیت پک تو پروژه اصلی خودم استفاده کنم.ولی از اون راه هم برای استفاده از این پروژه رفتم ولی ارور میده

 Failed to resolve: com.github.ebraminio:DroidPersianCalendar:v6.1.1
در حالیکه چند تا پروژ]دیگه رو چک کردم ارور نداشت.
در این مورد راهنمایی ندارین؟
در این مورد هم جی پی ال صدق میکنه؟

**Comment by ebraminio** [comment]
بله مجوز رو تغییر نمیده، است خود من هم تمایل نداشتم که این برنامه رو با
جی‌تی‌ال منتشر کنم ولی از اونجایی که از کتابخانه‌هایی استفاده کردم که
جی‌تی‌ال بودن و کسانی که مشارکت کردن با همین شرایط مشارکت کردن کاری
نمی‌تونم در این رابطه کنم ولی شاید اگه چنین نبود فکر کتابخونه کردن برنامه
هم میوفتادم به خاطر همین توصیه‌ام این هست که از سورس یاد بگیرید ولی جداگانه
پیاده‌سازی کنید ممنونم

در تاریخ شنبه ۱۴ سپتامبر ۲۰۱۹،‏ ۱۵:۳۰ arash-brz <notifications@github.com>
نوشت:

**Comment by arash-brz** [comment]
ممنون از شما
