### ISSUE TITLE
جدا کردن بخش تقویم

### ISSUE THREAD

**Issue by yasin413** [ebraminio/DroidPersianCalendar#478]
سلام 
من میخوام برای یک پروژه دیگر یک تقویم ساده فاسی پیاده سازی کنم 
امکانش هست لطفا راهنماییم کنید که برای استفاده از تقویم در یک پروژه دیگر چه بخش هایی رو جدا کنم

**Comment by ebraminio** [comment]
سلام!
https://github.com/ebraminio/DroidPersianCalendar/tree/master/PersianCalendar/src/main/java/com/byagowi/persiancalendar/calendar
که سعی شده به باقی پروژه وابستگی نداشته باشد از آنجایی که منبع آن پروژه، پروژه مقابل بوده که با مجوز جی‌پی‌ال منتشر شده است 
https://code.google.com/archive/p/mobile-persian-calendar/
کار شما هم باید با شرایط مجوز سازگار باشد، اگر منظور بخش بیشتر و ظاهری برنامه باشد، جدا کردن آن احتمالاً کار سختی باشد که به همین دلیل استفادهٔ حمایت شده از پروژه نیست، ممنون و خسته نباشید
