### ISSUE TITLE
alarm

### ISSUE THREAD

**Issue by ali-libre** [ebraminio/DroidPersianCalendar#48]
سلام..
اگه میشه یه  الارم با تنظیمات بهش اضافه کنید...
مثلا اینکه چند دقیقه قبل اذان زنگ بزنه...
یا مثلا کدوم روز‌های هفته زنگ بزنه..
مثلا واسه همه روزهای هفته بجز دوشنبه ‌ها که سر کلاسم ده دقیقه قبل اذان زنگ بزنه...
ایولا  داری..

**Comment by ebraminio** [comment]
سلام توسط @hamidsafdari انجام شد :)
