### ISSUE TITLE
Persian Calendar Library

### ISSUE THREAD

**Issue by Dariushm2** [ebraminio/DroidPersianCalendar#49]
Are you that generous to take time to make it a library? so lots of Iranian developers like me can use it in their apps as a widget easily.
Like this one: https://github.com/roomorama/Caldroid

**Comment by ebraminio** [comment]
هر چند پیشنهاد خیلی خوبی صادقانه بعید می‌دانم بتوانیم به این سمت حرکت کنیم :(

**Comment by Dariushm2** [comment]
چقدر دیر جواب دادید. وقتی دیدم جواب ندادید خودم دست به کار شدم و یه کتابخونه از پروژه شما ساختم. با اینکه شما زحمت زیادی کشیدین اما تبدیلش هم خیلی زحمت داشت و زمان برد. باید یه سری امکانات دیگه بهش اضافه کنم و تا چند وقت دیگه منتشرش می کنم.

    On Friday, December 18, 2015 5:58 PM, ebraminio <notifications@github.com> wrote:
 

 هر چند پیشنهاد خیلی خوبی صادقانه بعید می‌دانم بتوانیم به این سمت حرکت کنیم :(—
