### ISSUE TITLE
باگ ها در نسخه 4.1.2

### ISSUE THREAD

**Issue by mozaffari** [ebraminio/DroidPersianCalendar#51]
با سلام 
چند مشکل کوچک در نرم افزار هست 
اول: با وجود انتخاب ماه های دری باز هم نرم افزار در قسمت که نشانی کردم اسم ماه ایرانی را نمایش میدهد

![2015-06-13 22 25 15](https://cloud.githubusercontent.com/assets/8011883/8145413/b23d6252-121c-11e5-8dde-aa0416dcffe0.png)

دوم: با غیر فعال کردن گزینه قالب 24 ساعته باز هم
 اوقات شرعی به قالب 24 ساعته نمایش داده میشود

![2015-06-13 22 26 09](https://cloud.githubusercontent.com/assets/8011883/8145412/b20b07bc-121c-11e5-9e5a-5d97baa433f5.png)

![2015-06-13 22 26 50](https://cloud.githubusercontent.com/assets/8011883/8145411/b1e0da78-121c-11e5-813f-6af0e81776db.png)

سوم: در این مورد زیاد مطمین نیستم چون اخیرا در گوشی گلکسی اس 5 خود با یک مشکل برخوردم که گوشیم زیاد داغ میشود 
با نرم افزار battery doctor دیدم نرم افزار تقویم فارسی چهارمین مصرف کننده باطری هست

![screenshot_2015-06-13-22-08-29](https://cloud.githubusercontent.com/assets/8011883/8145432/78a6e8aa-121d-11e5-8385-b192aeb4e437.png)

نسخه تقویم من: 4.1.2
نسخه اندروید: 5.0
گوشی: Galaxy S5

**Comment by mozaffari** [comment]
![screenshot_2015-06-13-22-08-29](https://cloud.githubusercontent.com/assets/8011883/8145429/55c17706-121d-11e5-8447-c8f9f5b98bd5.png)

**Comment by ebraminio** [comment]
@hamidsafdari گرامی فکر می‌کنم مشکل اول حل شده باشد، آیا درست متوجه شده‌ام؟

@behdad222 با توجه به اینکه در کد مرتبط ویرایش داشته‌اید، تمایل دارید مشکل دوم را انجام حل کنید؟ :)

**Comment by behdad222** [comment]
@ebraminio چک میکنم

**Comment by behdad222** [comment]
@ebraminio مشکل دوم هم وجود نداره طبق تست من
البته یادم نمیاد کد قبلی رو تغییر داده باشم
و فقط به ویو جدید منتقلش کردم
به هر حال الان درسته
![screenshot_ -](https://cloud.githubusercontent.com/assets/3942191/12857851/bd2f3302-cc61-11e5-93d1-8f98c48855df.png)

**Comment by ebraminio** [comment]
بسیار خب پس باگ را با اجازه می‌بندم، چون دربارهٔ سوم من اطمینان ندارم مشکلی وجود داشته باشد یا اگر وجود داشته باشد به سادگی قابل رفع باشد. ممنون از همگی
