### ISSUE TITLE
نحوه تبدیل تارخی میلادی که از فید گرفته شده

### ISSUE THREAD

**Issue by nemati456** [ebraminio/DroidPersianCalendar#54]
سلام مهندس جان
من یک تاریخ دارم که از فیل خوان گرفتم به این صورت هست 
13 Aug 2015 19:19
میشه رانمایی بفرمایید مه چه جوری تبدیلش کنم به شمسی با تشکر

**Comment by ebraminio** [comment]
اطلاعی ندارم
