### ISSUE TITLE
جدا کردن پکیج تقویم به عنوان ماژول

### ISSUE THREAD

**Issue by Pedramrn** [ebraminio/DroidPersianCalendar#56]
سلام

خسته نباشید کارتون جای قدر دانی داره.

نکته ای که من متوجه شدم در طراحی قسمت مربوط به پکیج تقویم  و وابستگی اون به پکیج برنامه اصلی و کلاس یوتلیز شدم

برای استفاده از این تقویم در برنامه های دیگه این موضع مشکل ایجاد میکنه

به نظرم اگه این مشکل در طراحی رو رفع کنید و قسمت تقویم بصورت یک مازول یا لایبری دربیارید خیلی راحت تر میشه پروژه رو مدیریت کرد و با خیال راحت توسعه داد.

در کل خیلی بهتر میشه اگه این ماژول رو به صورت یک پکیج  قابل دانلود از جی سنتر در بیارین

**Comment by hamidsafdari** [comment]
@Pedramrn, حرف شما به جاست و مشکل از AbstractDate شروع میشه. مخصوصا دو متد getMonthsList و getMonthName. علاوه بر این PersianDate و CivilDate یک متد دیگه نیز به نام getDayOfWeekName دارن که مشکل رو بیشتر میکنه.

اگه به کلاس java.util.Date مراجعه کنید دیده میشه که اصلا نام ماه ها و روزهای هفته در این کلاس درج نشده.  جایی هم که نیاز بوده (مثل متد toString) از یک کلاس به اسم LocaleData استفاده شده که مثل اینکه متن باز نیست.

برای حل این مشکل میشه متدهای مذکور رو از AbstractDate برداشت و از یک کلاس دیگه استفاده کرد مثل DateFormatUtils که دارای متدهایی باشه که تاریخ مورد نظر رو به صورت مطلوب فرمت کنه.

فقط اینکه طراحAbstractDate آقای @ebraminio  هستن و من هم فکر کردم اول باید اجازه ایشون باشه و بعد درش تغییرات آورده بشه.

**Comment by ebraminio** [comment]
قسمت مبدل تقویم از پروژه دیگری آمده که با توجه به مجوز جی‌پی‌ال مناسب برای پروژه غیر متن‌باز نیست.

https://code.google.com/p/mobile-persian-calendar/

**Comment by hamidsafdari** [comment]
@Pedramrn, this branch https://github.com/ebraminio/DroidPersianCalendar/tree/generalize_abstract_date contains code that tries to modularize the calendar package.

Could you please have a look at it and tell me if this is what you want?
