### ISSUE TITLE
اصلاح ماه قمری

### ISSUE THREAD

**Issue by yooshimooshi** [ebraminio/DroidPersianCalendar#57]
با سلام
من سورس تقویم شما رو گرفتم و دارم روش کار میکنم و متوجه شدم مشکلی در تاریخ  قمری آن وجود دارد
از ماه رمضان امسال ترتیب ماههای 30 روزه و 29 روزه که یکی در میان است جابجا حساب می شود
به طور مثال رمضان 29 روزه و شوال 30 روزه و به همین ترتیب ..
که باید برعکس باشد
آیا برای این مشکل راه حلی وجود دارد ؟
با تشکر

**Comment by ebraminio** [comment]
ممنون دوست گرامی احتمالا تنها راه حل آن افزودن گزینه‌ای جهت اصلاح روز قمری است به همین دلیل با #53 ادغام می‌کنم
