### ISSUE TITLE
کپی به کلیپ‌برد

### ISSUE THREAD

**Issue by ebraminio** [ebraminio/DroidPersianCalendar#67]
<div dir="rtl">
از یکی از نظرات کاربران گرامی:

[...]
در بخش date converter، اگر بتوان کاری کرد که هنگام تپ کاربر روی تاریخ های نتیجه، همان عبارت مثلا « 21 آذر 94 » در کلیپ بورد کپی شود،
[...]
</div>

**Comment by hamidsafdari** [comment]
![device-2016-01-08-184532 50](https://cloud.githubusercontent.com/assets/5158006/12199931/6874a614-b639-11e5-8790-4f581861e86f.png)
![device-2016-01-08-184552 50](https://cloud.githubusercontent.com/assets/5158006/12199929/685dfff4-b639-11e5-9d79-d3ec4d1fd125.png)
![device-2016-01-08-184606 50](https://cloud.githubusercontent.com/assets/5158006/12199930/6864ec38-b639-11e5-97d5-f448eb4224c5.png)

**Comment by hamidsafdari** [comment]
روی هر کدام از تاریخ ها که تپ کنید به کلیپ بورد کپی می شود.
