### ISSUE TITLE
بررسی ویجت بهتر و افزودن اوقات شرعی به ویجت

### ISSUE THREAD

**Issue by ebraminio** [ebraminio/DroidPersianCalendar#68]
<div dir="rtl">قسمتی از یک ایمیل کاربری محترم: [...] فقط کاشکی ویجتهای بهتری میذاشتی براش که اوقات شرعی رو هم داشته باشه [...]</div>

**Comment by behdad222** [comment]
@ebraminio اینو نگفتم به من بدی!
ولی چشم
سعیم رو میکنم

**Comment by ebraminio** [comment]
آها :) البته فقط جهت امکان‌سنجی اساین کرده بودم

**Comment by ebraminio** [comment]
#41
