### ISSUE TITLE
نمایش انگلیسی تاریخ

### ISSUE THREAD

**Issue by ebraminio** [ebraminio/DroidPersianCalendar#70]
جداشده از #42

تاریخ میلادی بهتره که بصورت انگلیسی هم نشون داده بشه، یعنی: May/مه

**Comment by behdad222** [comment]
@ebraminio برای این کنار همون فارسیش انگلیسیش رو بزاریم؟

**Comment by ebraminio** [comment]
آره ولی اگه ممکنه عدد هم وجود داشته باشه برای انواع تاریخ‌ها

**Comment by behdad222** [comment]
@ebraminio یعنی چی؟

**Comment by ebraminio** [comment]
مه/May - ۵

**Comment by behdad222** [comment]
این پیاده شد ولی به نظر میرسه بد دراومد
فعلا انجام نشد
