### ISSUE TITLE
App crashes to load drawer on kitkat

### ISSUE THREAD

**Issue by hamidsafdari** [ebraminio/DroidPersianCalendar#73]
Tapping on the drawer icon on the top right corner cause the app to crash:

![device-2015-12-29-063541](https://cloud.githubusercontent.com/assets/5158006/12028555/aaf3ddd4-adf6-11e5-9e1a-49c0519b673d.png)

with this stack trace:

![2015-12-29-063606_907x390_scrot](https://cloud.githubusercontent.com/assets/5158006/12028571/df49562c-adf6-11e5-8054-8a683b828ca0.png)

**Comment by behdad222** [comment]
@hamidsafdari دمت گرم من چندبار دیده بودم اکسپشن میده ولی هیچ وقت تو خونه نبودم که لاگش رو ببینم
این آخرین بیلد هست؟

**Comment by hamidsafdari** [comment]
بله بهداد جان آخرین بیلده.
من اگه وقت پیدا کنم امروز و فردا درستش می کنم اما شما از ما بهتری

**Comment by hamidsafdari** [comment]
The exception problem is solved now:
![device-2016-01-08-132827](https://cloud.githubusercontent.com/assets/5158006/12194282/713ca184-b60c-11e5-8a19-f4688b4d0dd8.png)

Also fixed a little layout problem in that the icon and text would be unaligned in phones that have set an rtl language. The result:
![device-2016-01-08-132907 90](https://cloud.githubusercontent.com/assets/5158006/12194392/504d9a86-b60d-11e5-8a91-5dc53b6b8646.png)

![device-2016-01-08-132944 60](https://cloud.githubusercontent.com/assets/5158006/12194365/1012caae-b60d-11e5-8a9e-a7f52573faf9.png)
