### ISSUE TITLE
حالت های پیشنهادی برای ویجت

### ISSUE THREAD

**Issue by rastikerdar** [ebraminio/DroidPersianCalendar#74]
![pic۱](https://cloud.githubusercontent.com/assets/3116038/12044297/3374b568-aea4-11e5-9a08-158a6428cbdf.png)
![pic۲](https://cloud.githubusercontent.com/assets/3116038/12044300/3754c916-aea4-11e5-9cb1-27ab7c0b1279.png)
![pic۳](https://cloud.githubusercontent.com/assets/3116038/12044309/580b63a4-aea4-11e5-9fd5-ac490ddcc3e0.png)
![pic۴](https://cloud.githubusercontent.com/assets/3116038/12044313/68786282-aea4-11e5-85d2-facbe5dee900.png)

من خودم دوتای آخری رو ترجیح میدم

**Comment by behdad222** [comment]
بسیار عالی

**Comment by ebraminio** [comment]
+1
