### ISSUE TITLE
مشکل دیتابیس در شروع برنامه

### ISSUE THREAD

**Issue by behdad222** [ebraminio/DroidPersianCalendar#78]
تو اولین اجرا برنامه اکسپشن میده

![screenshot from 2016-01-23 11 39 35](https://cloud.githubusercontent.com/assets/3942191/12529295/1cb05762-c1c6-11e5-950f-aad246da94a2.png)

**Comment by hamidsafdari** [comment]
الان باید درست شده باشه

**Comment by behdad222** [comment]
@hamidsafdari پوش کن
