### ISSUE TITLE
موقع پخش اذان اکسپشن داد

### ISSUE THREAD

**Issue by behdad222** [ebraminio/DroidPersianCalendar#81]
فکر کنم این اکسپشن باعث بشه نتیفیکیشن اذان نره کلا

![screenshot from 2016-02-10 18-51-18](https://cloud.githubusercontent.com/assets/3942191/12955795/f229ca8c-d039-11e5-81fa-ec9239806114.png)
![screenshot from 2016-02-10 18-51-25](https://cloud.githubusercontent.com/assets/3942191/12955796/f254994c-d039-11e5-8d35-365ca5492148.png)

**Comment by hamidsafdari** [comment]
@ebraminio 
به جای اسکرینشات لطفا خود ستک ترس رو بندازید اینجا. 
براش اسکرولبار میاد مشکلی نداره.

**Comment by ebraminio** [comment]
حدس می‌زنم هنگام اذان اینستنس دیگری از برنامه ایجاد شده که از آنجایی که اس‌کیولایت قابلیت دو تماس همزمان ندارد و اندروید پیشاپیش خود برای آن احتمالاً قفلی گذاشته باشد که باعث کرش برنامه شده است. به نظرم با توجه به اینکه اسکیولایت هنوز کاربری اساسی در این برنامه ندارد می‌شود به حذفش فکر کرد که در آینده مشکلی به وجود نیاورد یا راه حلی باید در نظر گرفته شود که دقیقاً یک نمونه از برنامه در اندروید اجرا شود.

**Comment by hamidsafdari** [comment]
میشه کلاس دیتابیش رو سینگلتون کرد. این مشکل رو رفع میکنه.
زحمت نمیشه این رو به من اساین کنید.

**Comment by behdad222** [comment]
خوندن این اسکرین شات برای من راحت تر از اون لاگ هست
ولی از به بعد اسکرین شات نمیزارم

**Comment by ebraminio** [comment]
من هم اسکرین‌شات رو بیشتر دوست دارم :)

**Comment by ebraminio** [comment]
به ناچار برای رفع این مشکل و خطاهای غیر منتظره که قابل به رفع آن‌ها نبودم پیاده‌سازی اس‌کیولایت را حذف کردم ولی تمام قابلیت‌ها آن را با جی‌سن پیاده‌سازی کردم و برای شهرهایی که در مرتب‌سازی مشکل داشتند نیز راه حلی به کار گرفتم به علاوه ذخیرهٔ جی‌سن دارای مختصات جغرافیایی در کنار سایر مشخصات است و کد جداگانهٔ مختصات نیز حذف شد.
