### ISSUE TITLE
تغییر شکل کعبه در قطب نما

### ISSUE THREAD

**Issue by behdad222** [ebraminio/DroidPersianCalendar#86]

**Comment by ebraminio** [comment]
![screen shot 2016-02-11 at 11 21 57 am](https://cloud.githubusercontent.com/assets/833473/12971564/c401d30c-d0b1-11e5-8c62-673dd125422d.png)
![screen shot 2016-02-11 at 11 21 40 am](https://cloud.githubusercontent.com/assets/833473/12971565/c4641b5c-d0b1-11e5-9fc1-9719cc00c62c.png)

به نظرم یکی از این دو که علائم سجده در دو فونت نسخ و نستعلیق اردو هستند را انتخاب کنیم

همین نویسه در سایر قلم‌ها: http://www.fileformat.info/info/unicode/char/06e9/fontsupport.htm

[Noto۩.zip](https://github.com/ebraminio/DroidPersianCalendar/files/126027/Noto.zip)

**Comment by ebraminio** [comment]
http://emojipedia.org/kaaba/
یک سری از آیکون‌های کعبه را که اکثراً آزاد هستند فهرست کرده، به نظر من Emojione آن عالی است
